### ISSUE TITLE
***CRITICAL BUG*** Error: The system cannot find the file specified | NetworkInformationException | at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()

### ISSUE THREAD

**Issue by firephantomassasin** [Azure/azure-storage-net#1030]
### Which service(blob, file, queue, table) does this issue concern?
Azure blob storage

### Which version of the SDK was used?
11.1.7

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.7.2

### What problem was encountered?

Exception Type: 
NetworkInformationException

Message: 
The system cannot find the file specified

Stack Trace: 
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_FixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()
   at System.Net.CookieContainer..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.Azure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.<>c.<.cctor>b__12_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.get_Instance()
   at Microsoft.Azure.Storage.Shared.Protocol.HttpClientFactory.<>c.<.cctor>b__5_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.Storage.Shared.Protocol.HttpClientFactory.get_Instance()
   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.Blob.CloudBlockBlob.<DownloadTextAsync>d__72.MoveNext()

### How can we reproduce the problem in the simplest way?
It is happening when running in azure web app, using P1V3 (Dual core specs), only 1 server is encountering this kind of issue out of 3 servers. We are using VNET integration with WEBSITE_VNET_ROUTE_ALL = 1.

### Have you found a mitigation/solution?
None.

**Comment by amnguye** [comment]
This looks like it requires using azure web apps to reproduce, this looks like it might be more of an issue in azure web apps on how they're using the library. Could you be more specific on what could be triggering this in the web app? We would like to see what in the storage library could be throwing this error. Unfortunately ` Microsoft.Azure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.get_Instance()` gets called at any http request sent, so it's hard to tell what's even happening here. Any more sort of logs would be helpful.

**Comment by firephantomassasin** [comment]
@amnguye yes you are right. This only happens when using azure web apps. 

This is the only logs that we are receiving.

Exception Type:
NetworkInformationException

Message:
The system cannot find the file specified

Stack Trace:
at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()
at System.Net.NetworkInformation.SystemIPGlobalProperties.get_FixedInfo()
at System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()
at System.Net.CookieContainer..ctor()
at System.Net.Http.HttpClientHandler..ctor()

Do you have any ideas on what are this SystemIPGlobalProperties, and why is it the error message is about "The system cannot find the file specified", does this mean that there is a missing file on azure web app? Could you also help me to escalate this issue on the azure web app team?

**Comment by amnguye** [comment]
I saw that you already opened a Incident Issue through Portal. https://github.com/Azure/azure-sdk-for-net/issues/17498#issuecomment-744523270

Unfortunately there's nothing more I can do to escalate the issue since you have already taken all the correct measures and steps to do so. I would continue following up on that incident report so they can better resolve and help your issue. With the incident you opened through portal, they are able to look at logs (if they are available) and other analytics to help with the problem (unfortunately I do not have access to this).
