### ISSUE TITLE
StorageException thrown in 4.2.1

### ISSUE THREAD

**Issue by miparnisari** [Azure/azure-storage-net#148]
Using the NuGet package "WindowsAzure.Storage" version 4.2.1, the following C# code...

	
 ```C#
    try
	{
		int maxRetryCount = 3;
		var blobRequestOptions = new BlobRequestOptions
		{
			RetryPolicy = new ExponentialRetry(TimeSpan.FromSeconds(5), maxRetryCount),
			MaximumExecutionTime = TimeSpan.FromMinutes(60),
			ServerTimeout = TimeSpan.FromMinutes(60)
		};
		using (var fileStream = File.Create(localPath))
		{
			blockBlob.DownloadToStream(fileStream, null, blobRequestOptions);
		}
	}
	catch (Exception e)
	{
		logger.Error(string.Format("Downloading {0}: {1}", blobName, e.Message));
	}
```

...sometimes throws the following exception (mainly when downloading a big blob, ~500 MB, from a storage account that is far away from the website):

**[06/29/2015 17:53:44 > 324d4d: ERR ] Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.
[06/29/2015 17:53:44 > 324d4d: ERR ]    --- End of inner exception stack trace ---
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadText(IAsyncResult asyncResult)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)
[06/29/2015 17:53:44 > 324d4d: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<TryExecuteAsync>d__9.MoveNext()
[06/29/2015 17:53:44 > 324d4d: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.RecurrentTaskSeriesCommand.<ExecuteAsync>d__0.MoveNext()
[06/29/2015 17:53:44 > 324d4d: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[06/29/2015 17:53:44 > 324d4d: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/29/2015 17:53:44 > 324d4d: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[06/29/2015 17:53:44 > 324d4d: ERR ]    at System.Threading.ThreadHelper.ThreadStart()**

How can I prevent this??

**Comment by miparnisari** [comment]
Solution posted here: http://stackoverflow.com/questions/31128977/storageexception-when-downloading-a-large-file-over-a-slow-network/

**Comment by mirobers** [comment]
The stack trace provided is for a blob upload (CloudBlockBlob.UploadText). You may want to check your timeout settings for the call to UploadText to make sure you are allowing enough time.

**Comment by miparnisari** [comment]
@mirobers my code doesn't upload anything.

**Comment by mirobers** [comment]
It looks like you are using WebJobs, based on the stack trace:
Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand

So the error is coming from a WebJobs call to storage. Could you describe a little about your setup, in particular how you are using WebJobs?

**Comment by miparnisari** [comment]
@mirobers it's a triggered webjob that downloads zip files from a storage account and decompresses them into the website. 

Let me know if you need more information.

**Comment by bspunie** [comment]
I am experiencing the same issue. Following code throwing same exception to download 1.5 GB file from storage account. 

await blob.DownloadToFileAsync(<path>, FileMode.Create);

I have a web job which downloads the file and this exception is sporadic in nature. Sometimes it passes, mostly fails. Just to be clear that web job does not timeout, its only above line of code causing the exception.

Any help would be nice.

**Comment by mirobers** [comment]
Thanks for reporting this. Are you seeing the same stack trace as above (WebJobs, EndUploadText, etc.)? Or are you seeing a stack trace related to your call to DownloadToFileAsync? If your own call is timing out on the client, you will need to increase your timeout.

**Comment by bspunie** [comment]
Here is my stack trace

[12/02/2015 10:22:15 > 98fbad: ERR ] Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.
[12/02/2015 10:22:15 > 98fbad: ERR ]    --- End of inner exception stack trace ---
[12/02/2015 10:22:15 > 98fbad: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
[12/02/2015 10:22:15 > 98fbad: ERR ]    at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadText(IAsyncResult asyncResult)
[12/02/2015 10:22:15 > 98fbad: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)
[12/02/2015 10:22:15 > 98fbad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/02/2015 10:22:15 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/02/2015 10:22:15 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<TryExecuteAsync>d__9.MoveNext()
[12/02/2015 10:22:16 > 98fbad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.RecurrentTaskSeriesCommand.<ExecuteAsync>d__0.MoveNext()
[12/02/2015 10:22:16 > 98fbad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[12/02/2015 10:22:16 > 98fbad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/02/2015 10:22:16 > 98fbad: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[12/02/2015 10:22:16 > 98fbad: ERR ]    at System.Threading.ThreadHelper.ThreadStart()

**Comment by pemari-msft** [comment]
As @mirobers  mentioned, here's your error: ``The client could not finish the operation within specified timeout.``

This indicates that the timeout being used is too small for the request. Please increase the timeout and see if that solves the issue. However, this stack trace indicates that it is being thrown from an Upload call -- ``EndUploadText`` is in the stack. I'm not sure where you're doing the Upload but it is seemingly related to the WebJobs code. If so, I'd recommend following up with them as they may have more insight.

**Comment by bspunie** [comment]
Thanks for the quick reply!

I tried BlobRequestOptions.ServerTimeout = TimeSpan.FromMinutes(30) but didn't help.

It times out after 8 minutes. As @miparnisari mentioned, I am also not uploading anything. I dont know why it is internally calling that method. Looking at the stack trace, I suspect Microsoft.WindowsAzure.Storage.Core to be the cause based on inner exception

Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadText(IAsyncResult asyncResult)
Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)

I am looking at web job forum meanwhile. Cheers :)

**Comment by mirobers** [comment]
Okay, this does look like the same issue then. Web Jobs is issuing the upload request on its own. We will need to check with the Web Jobs team and get back to you.

**Comment by bspunie** [comment]
Thanks @mirobers

**Comment by mathewc** [comment]
Hey guys, I'm from the WebJobs team. For the persons on this thread seeing timeouts with WebJobs SDK code in the stack trace (e.g. **Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand**), when your job function includes a TextWriter/TraceWriter parameter and writes logs to it, the SDK will periodically flush those logs to blob storage, so you can see the output in the WebJobs Dashboard. Generally this is not much data, so there shouldn't be any timeouts. Hopefully you're not trying to log huge amounts of data to the function log. I haven't heard other WebJobs SDK users complain of this, so it might be that you're doing something unusual, or you're saturating your network/connections causing the timeouts?

There is a way to configure the CloudBlobClient that the SDK uses for this - you can set the **CloudBlobClient.DefaultRequestOptions.ServerTimeout** to a larger value (the SDK just accepts whatever the Azure Storage default is). However, I'm not yet sure increasing that is the right thing to do.

**Comment by miparnisari** [comment]
Hey @mathewc, I don't have the code available anymore, but you may be right because I do remember that it did an awful lot of logging.

**Comment by rohankulkarni21** [comment]
Hi

I am using WebJobs SDK 1.1.1 and WindowsAzure.Storage 5.0.2 in a Worker Role where QueueTrigger function is written which take a message from queue and does a long running process.

My worker role was running fine earlier but now there are about 200000 message in the queue.
I am into UAT and my worker role is shutting down with the following error:
It is a show stopper for us. please help

An unhandled exception occurred. Type: Microsoft.WindowsAzure.Storage.StorageException Process ID: 14552
Process Name: WaWorkerHost
Thread ID: 532
AppDomain Unhandled Exception for role deployment28(71).CE.AO.Analytics.CalculationCSvc.CE.AO.Analytics.CalculationWorker_IN_0
Exception: The client could not finish the operation within specified timeout.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Queues.Listeners.UpdateQueueMessageVisibilityCommand.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Inner Exception: The client could not finish the operation within specified timeout.

**Comment by richardlee713** [comment]
Is there yet a solution to this ?
I have a continuous webjob that fails after about 8 minutes with the following:

An unhandled exception of type 'Microsoft.WindowsAzure.Storage.StorageException' occurred in Microsoft.Azure.WebJobs.Host.dll

Additional information. The client could not finish the operation within specified timeout.
