### ISSUE TITLE
Exception thrown in WinPhone8 deployment

### ISSUE THREAD

**Issue by sagoo33** [Azure/azure-storage-net#167]
I am trying to add a message into a message queue, everything works fine in the Win8 emulator:

            {

 try
            {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(connection);

                CloudQueueClient queueClient =
                    storageAccount.CreateCloudQueueClient();

                CloudQueue queue = queueClient.GetQueueReference("myQueue");

                await queue.CreateIfNotExistsAsync();
                //   var m = queue.GetMessage();

                CloudQueueMessage message = new CloudQueueMessage("New Message 1");
                await queue.AddMessageAsync(message);

            }
            catch (Exception ex)
            {
                txtError.Text = ex.ToString();

            }

When I deploy this and run it (in either release or debug) I receive the following error:

System.ArgumentOutOfRangeException: The argument 'offset' is larger than maximum of '6176'
Parameter name: offset
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertInBounds[T](String paramName, T val, T min, T max)
   at Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.Flush()
   at System.Xml.XmlWellFormedWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at Microsoft.WindowsAzure.Storage.Queue.Protocol.QueueRequest.WriteMessageContent(String messageContent, Stream outputStream)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<>c__DisplayClass3b.<<AddMessageAsync>b__3a>d__3d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ThinClient.Win8.MainPage.<AddNewMessage>d__3.MoveNext()

I have the following packages installed:

  package id="Microsoft.Data.Edm" version="5.6.4" targetFramework="wpa81" 
  package id="Microsoft.Data.OData" version="5.6.4" targetFramework="wpa81" 
 package id="System.Spatial" version="5.6.4" targetFramework="wpa81" 
 package id="WindowsAzure.Storage" version="5.0.0" targetFramework="wpa81"

**Comment by pemari-msft** [comment]
Hi @sagoo33,

Can you give a little more information about when you're calling the above code snippet? Could you perhaps provide a full repro? I wasn't able to repro myself.

Thanks!

**Comment by sagoo33** [comment]
Hi, thanks for your reply.
I am on Windows 10(latest) and calling the above from a button click. 

The project is very simple, new win 8 universal app> add a button> create a click handler> paste the above code> deploy to win 8 phone> click button > exception thrown.
I could provide the project if necessary?

Unfortunately I have now upgraded my windows phone to the Win 10 insider preview thinking that deploying a Win 10 Universal app might fix work, without realising the mobile version is too old to deploy to from my win 10 machine, so I can't test this anymore until a new win 10 mobile version is out

**Comment by pemari-msft** [comment]
I'm also on Win10, made a new universal app and ran the repro snippet on a button click and then deployed it to a device succesfully. You could certainly try sending the project over and I'll try that if you'd like, if that doesn't work we could try to work through it again when you're able to repro yourself as well.

**Comment by sagoo33** [comment]
Hi, I have now installed the latest version of Win10 (10512) and deployed the Win10 UAP to the phone successfully. The app doesn't throw that error when the button is clicked on Win10.
Hopefully it was just a freak thing with my particular Win8 phone and Win 10 dev machine.
Thanks for your time :)
