### ISSUE TITLE
version 6.0.0.0 NOT work with mooncake (China Azure)

### ISSUE THREAD

**Issue by caserzer** [Azure/azure-storage-net#184]
Error in NLogBlobWatcher Initialize()Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 680
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 820
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 201
   at Microsoft.Telematics.CommonServices.NLogBlobWatcher.Initialize() in d:\Builds\88\QorosTSP\Publish_PDP_7PrePrd_2.0.6_SDK27\Sources\6-Common\Common Service\Logging\NLog\NLogBlobWatcher.cs:line 79
Request Information
RequestID:c3d3c562-0001-0049-2b50-fb599e000000
RequestDate:Wed, 30 Sep 2015 07:19:43 GMT
StatusMessage:The value for one of the HTTP headers is not in the correct format.

**Comment by pemari-msft** [comment]
Sorry about that -- the new features should now work with 6.0.0 in Mooncake. Please let us know if you have any further issues.
