### ISSUE TITLE
6.0 breaking bug - container.CreateIfNotExists() throws an exception.

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-storage-net#185]
We just upgraded to 6.0 and noticed an exception getting thrown every time.

https://ci.appveyor.com/project/Exceptionless/foundatio/build/3.0.508

```csharp
            var account = CloudStorageAccount.Parse(connectionString);
            var client = account.CreateCloudBlobClient();
            _container = client.GetContainerReference(containerName);
            _container.CreateIfNotExists();
```

```
Microsoft.WindowsAzure.Storage.StorageExceptionThe remote server returned an error: (400) Bad Request.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync(RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs: line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs: line 197
   at Foundatio.Storage.AzureFileStorage..ctor(String connectionString, String containerName) in AzureFileStorage.cs: line 21
   at Foundatio.Azure.Tests.Storage.AzureStorageTests.GetStorage() in AzureStorageTests.cs: line 16
   at Foundatio.Tests.Storage.FileStorageTestsBase.<ResetAsync>d__6.MoveNext() in FileStorageTestsBase.cs: line 110
```

We are using the latest version of the azure storage emulator for our tests.

Code can be found here: https://github.com/exceptionless/Foundatio

**Comment by pemari-msft** [comment]
Can you please confirm that you're using Azure Storage Emulator 4.2 found here: https://azure.microsoft.com/en-us/downloads/

**Comment by niemyjski** [comment]
I'm running 4.1... That page doesn't do anything when I click on the install link, there was no notification in Visual Studio or the Web Platform Installer. How is anyone supposed to know that there is an update :-1:.

**Comment by niemyjski** [comment]
Thanks for your help, I'll check to see that it's fixed later but there needs to be some kind of notification that an update is available.. I could have spent a whole day trying to track this down.

**Comment by pemari-msft** [comment]
Every time there's a new Storage Services version (x-ms-version), the Storage Emulator needs to be updated to emulate these new types of requests. The Client Library is linked to one Storage Service version (in this case, 2015-04-05). Thus, updating the client library will start making these new types of requests that the old emulator does not know how to handle.

I'm not sure what you mean when you say the page doesn't do anything when you click the install link -- I was able to download the new version from there. We will, going forward, add a section to the readme/changelog about the storage emulator in order to make the above clearer. We can also try to make it more clear that a new version is available in the future. Please feel free to share any suggestions you may have. Thanks!

**Comment by GuardRex** [comment]
> I'll check to see that it's fixed later but there needs to be some kind of notification that an update is available.. I could have spent a whole day trying to track this down.

Which is why I was suggesting that the Storage team have an Announements repo (https://github.com/Azure/azure-storage-net/issues/173) ... just like the .NET teams use that we could subscribe to. When there is an update, we would all be informed immediately through Github.

That idea was shot down for no good reason IMHO. Oh, well. I suppose the guessing game will have to continue.

**Comment by niemyjski** [comment]
That kind of stinks. I wish they would make things simpler for us devs :). Thanks again for all of your help.

**Comment by pemari-msft** [comment]
We are definitely interested in making it as easy as possible for developers. Because of the feedback we’ve heard today, we’ve updated our Readme to include specific information regarding overall versioning and the storage emulator and we are planning to include this information in our changelog for each release going forward if the emulator will be affected. 

If you're interested in storage announcements, the [Azure Blog, filtered for Storage/Backup](https://azure.microsoft.com/en-us/blog/topics/storage-backup-and-recovery/) is where we post our overall updates for the service and specific libraries. If you're looking for more specific technical updates, the [changelog or releases page](https://github.com/Azure/azure-storage-net/releases) is the place to be. We will include relevant Emulator lines in the future there as well. 

Thanks again for your feedback.

**Comment by Zhaph** [comment]
I'm not seeing any reference to the updated Storage Emulator anywhere on the Azure Blog pages around the [announcement of the new services within Blob Storage](https://azure.microsoft.com/en-us/blog/azurecon-2015-azure-storage-announcements/) nor on your "changelog or releases" page?

**Comment by pemari-msft** [comment]
Like I said, we will include lines in the changelog going forward and I've added an emulator section to our [README page located at the root of this repository.](https://github.com/Azure/azure-storage-net#use-with-the-azure-storage-emulator)

**Comment by Zhaph** [comment]
Cool, sorry for missing that ;) Thanks.

**Comment by mobius127** [comment]
Hi,
I'm taking this error with Table Storage:

AnalysisDepartment.AzureMediaServices.Services.VideoTableStorageService - [ERROR] with Message:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableOperation.cs:line 44
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 52
   at AnalysisDepartment.AzureMediaServices.Services.VideoTableStorageService.ModifyVideo(VideoStorageModel video) in D:\ProyectosVSO\Project.AnalysisDepartmentWeb\AnalysisDepartmentWeb.AzureMediaServices\Services\Impl\VideoTableStorageService.cs:line 184

![image](https://user-images.githubusercontent.com/16031601/29210851-e3c019ea-7e95-11e7-8697-8d8d728d0a0d.png)
