### ISSUE TITLE
Missing/Wrong compilation definition "DNXCORE50"

### ISSUE THREAD

**Issue by EinarA** [Azure/azure-storage-net#214]
In Shared\Protocol\Constants.cs there is this section:

#elif ASPNET_K
#if DNXCORE50
                UserAgentComment = "(ASP.NET Core 5.0)";
#endif

Project file defines:

"compilationOptions": {
        "define": [ "ASPNET_K" ],

Which means that UserAgentComment is undefined and causes an exception when you try to call any API's.

"The value cannot be null or empty.
Parameter name: comment"

StackTrace:
   at System.Net.Http.Headers.HeaderUtilities.CheckValidComment(String value, String parameterName)
   at System.Net.Http.Headers.ProductInfoHeaderValue..ctor(String comment)
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpClientFactory.BuildHttpClient[T](RESTCommand`1 cmd, HttpMessageHandler handler, Boolean useVersionHeader, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Shared\Protocol\HttpClientFactory.cs:line 31
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 67

**Comment by pemari-msft** [comment]
Thanks for catching this. This was not a compilation constant defined by us, it was defined by the CoreCLR team. As you've determined, they removed it in rc1. We'll have a fix for this published ASAP. Thanks for your patience.

**Comment by pemari-msft** [comment]
We've pushed a fix to GitHub and we're in the process of releasing a 6.2.2-preview version to nuget that contains the fix.

**Comment by pemari-msft** [comment]
We've pushed the fix for this. Thanks again for the quick report and sorry for the inconvenience.
