### ISSUE TITLE
SymmetricKey exception when specifying a key length of 64

### ISSUE THREAD

**Issue by DarinMacRae** [Azure/azure-storage-net#222]
Using your own Sample project TableGettingStartedUsingResolver change the following code on line 50:

```csharp
      var key = new RsaKey("private:key1");     
```
to

```csharp
       var key = new SymmetricKey("symkey:mykey1", 64);
```
and you'll get the following exception:

```csharp
Microsoft.WindowsAzure.Storage.StorageException: One or more errors occurred. ---> System.AggregateException: One or mor
e errors occurred. ---> System.ArgumentOutOfRangeException: key must be 256 bits long
Parameter name: key
   at Microsoft.Azure.KeyVault.Cryptography.Algorithms.AesKw256.CreateEncryptor(Byte[] key, Byte[] iv)
   at Microsoft.Azure.KeyVault.SymmetricKey.<WrapKeyAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy.EncryptEntity(IDictionary`2 properties, String partitio
nKey, String rowKey, Func`4 encryptionResolver)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.GetPropertiesFromDictionary(IDic
tionary`2 properties, TableRequestOptions options, String partitionKey, String rowKey)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.<GetPropertiesWithKeys>d__9.Move
Next()
   at Microsoft.Data.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEn
umerable`1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPro
pertiesAnnotation projectedProperties)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightWriter.EndEntry(ODataEntry entry)
   at Microsoft.Data.OData.ODataWriterCore.<WriteEndImplementation>b__16()
   at Microsoft.Data.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.Data.OData.ODataWriterCore.WriteEndImplementation()
   at Microsoft.Data.OData.ODataWriterCore.WriteEnd()
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.WriteOdataEntity(ITableEntity en
tity, TableOperationType operationType, OperationContext ctx, ODataWriter writer, TableRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.BuildRequestForTableOperation(Ur
i uri, UriQueryBuilder builder, IBufferManager bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useV
ersionHeader, OperationContext ctx, TableRequestOptions options, String accountName)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass4.<InsertImpl>b__1(Uri uri, UriQueryBuilder b
uilder, Nullable`1 timeout, Boolean useVersionHeader, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, St
ring startLogMessage)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, Opera
tionContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, Opera
tionContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableReques
tOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptio
ns, OperationContext operationContext)
   at TableGettingStartedUsingResolver.Program.Main(String[] args) in C:\Source\azure-storage-net\Samples\GettingStarted
\EncryptionSamples\TableGettingStarted\Program.cs:line 84
```

1. If the code allows settings the key length to 64 it should "just work" and not throw an exception. So either disallow that value or support it correctly.

2. Why is there only one key length value to begin with? There are two keys being generated here, CEK and the KEK. Shouldn't they be allowed to have different key lengths, especially considering that one is an asymmetric key and the other is a symmetric key.

**Comment by pemari-msft** [comment]
Hi @DarinMacRae,

Thanks for the feedback. This occurs due to the code we have a dependency on, the KeyVault package. We redirected your comments to the KeyVault team and we're looking at ways we can have them provide this information differently so we could fail faster. For now, the earliest our code can detect it is when the encryption is attempted. Sorry about that! As soon as they make their relevant fix we'll go ahead and make this better.
