### ISSUE TITLE
Object reference not set to an instance of an object. on executing batch operation table.ExecuteBatch(batch)

### ISSUE THREAD

**Issue by adimkov** [Azure/azure-storage-net#226]
Hi, 
I got NRE on executing batch operation like this:
```C#
var batch = new TableBatchOperation();
foreach (var vid in videos)
{
batch.InsertOrReplace(VideoObjectEntity.ConvertToVideoObjectEntity(vid);
}
table.ExecuteBatch(batch);
```
I missed something?
```C#
Microsoft.WindowsAzure.Storage.StorageException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.GenerateRequestURI(Uri uri, String tableName) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\TableOperation.Common.cs:line 397
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.BuildRequestForTableBatchOperation(Uri uri, UriQueryBuilder builder, IBufferManager bufferManager, Nullable`1 timeout, String tableName, TableBatchOperation batch, Boolean useVersionHeader, OperationContext ctx, TableRequestOptions options, String accountName) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpRequestFactory.cs:line 157
   at Microsoft.WindowsAzure.Storage.Table.TableBatchOperation.<>c__DisplayClassa.<BatchImpl>b__6(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableBatchOperation.cs:line 155
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 849
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 619
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 632
   at Microsoft.WindowsAzure.Storage.Table.TableBatchOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableBatchOperation.cs:line 112
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.ExecuteBatch(TableBatchOperation batch, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 164
   at EarnHoney.Utilities.VideoUtils.PutVideoListIntoCache(IEnumerable`1 videos, Int32 channel) in ... secret code :)
```
Request Information
RequestID:
RequestDate:
StatusMessage:

LIB:
 Assembly Microsoft.WindowsAzure.Storage, Version=6.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Comment by pemari-msft** [comment]
Can you please specify what platform you're using? What project type?

**Comment by adimkov** [comment]
Windows 10 enterprise x64

Project: Class Library .Net Framework 4.5
Class  library utilised by Web Application .Net Framework 4.5

**Comment by pemari-msft** [comment]
We found a bug recently in this code path that can manifest itself as a nullref if one of the operations within the batch has a null partition key or a null row key where it's required. Can you please check that your batch does not have any null partition or row keys?

**Comment by adimkov** [comment]
Yes, you are right. I do update of key before insert but not before batch insert. Thanks.
