### ISSUE TITLE
'Cannot access a disposed object error' when partition key is null

### ISSUE THREAD

**Issue by ccrevola** [Azure/azure-storage-net#295]
When trying to insert into a table if the PartitionKey is not specified in the entity (ie null) you receive the following error:
Test Name:	AzureTableTests.TableTests.TestUserInsert
Test FullName:	AzureTableTests.TableTests.TestUserInsert
Test Source:	
Test Outcome:	Failed
Test Duration:	0:00:00.921

Result StackTrace:	
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AzureTableTests.TableTests.TestUserInsert() in C:\Development\Tools\UltrasoftwareTools\CLI\Ultrasoftware.AzureTable\tests\AzureTableTests\TableTests.cs:line 37
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 315
   at System.Net.Http.WinHttpResponseStream.CheckDisposed()
   at System.Net.Http.WinHttpResponseStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Net.Http.DelegatingStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Core.Util.StreamExtensions.<WriteToAsync>d__1`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\StreamExtensions.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 179
Result Message:	
One or more errors occurred. (Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.)
Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.
Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.

The above is the output from xUnit test:

    public void TestUserInsert()
        {
            var options = new AzureIdentityOptions
            {
                CloudStorageAccount = <insert account settings here>
                PartitionKey = <specify partition key here>
            };
            var storageAccount = CloudStorageAccount.Parse(options.CloudStorageAccount);

            // CreateAsync the table client.
            var tableClient = storageAccount.CreateCloudTableClient();

            // CreateAsync the table if it doesn't exist.
            var table = tableClient.GetTableReference("Identity");
            table.CreateIfNotExistsAsync().Wait();
            var insertOperation = TableOperation.Insert(new TestTable());
            var result = table.ExecuteAsync(insertOperation).Result;
            Assert.True(result != null);
        }
    public class TestTable : TableEntity
    {
        public TestTable()
        {
            RowKey = Guid.NewGuid().ToString();
            Id = RowKey;
        }

        public string Id { get; set; }
    }

If you specify the partition key even as empty string insert works, test passes. I was expecting an error on invalid partitionkey rather than an internal Http exception.

This was run on Windows 10 Professional, Visual Studio 2015 Professional. The target framework is: netcoreapp1.0

**Comment by esummers-msft** [comment]
Thank you for alerting us to this. We have filed it as a bug.

**Comment by pemari-msft** [comment]
Fixed in 7.2.0! Thanks for the report.
