### ISSUE TITLE
.NET Core TableEntity is throwing a storage exception on derived class properties

### ISSUE THREAD

**Issue by dlmelendez** [Azure/azure-storage-net#341]
#291

Looks like the fix for 291:
azure-storage-net/Lib/Common/Table/TableEntity.cs
`#elif NETCORE 
            IEnumerable<PropertyInfo> objectProperties = entity.GetType().GetTypeInfo().GetAllProperties();`
is causing this exception below. Why did you use GetAllProperties() instead of `entity.GetType().GetTypeInfo().GetProperties();` as suggested? Same repro as in 291 but now throws an exception. 7.2 throws exception, 7.1.3-preview works as expected.

Beginning Exception dump:
{Microsoft.WindowsAzure.Storage.StorageException: An item with the same key has already been added. Key: UserName ---> System.ArgumentException: An item with the same key has already been added. Key: UserName
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.WindowsAzure.Storage.Table.TableEntity.ReflectionWrite(Object entity, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\TableEntity.cs:line 315
   at Microsoft.WindowsAzure.Storage.Table.TableEntity.WriteEntity(OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\TableEntity.cs:line 280
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.GetPropertiesWithKeys(ITableEntity entity, OperationContext operationContext, TableOperationType operationType) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\Protocol\TableOperationHttpRequestFactory.cs:line 221
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.WriteOdataEntity(ITableEntity entity, TableOperationType operationType, OperationContext ctx, ODataWriter writer) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\Protocol\TableOperationHttpRequestFactory.cs:line 195
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableOperation[T](RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, Nullable`1 timeout, TableOperation operation, CloudTableClient client, HttpContent content, OperationContext ctx, TablePayloadFormat payloadFormat, ICanonicalizer canonicalizer, StorageCredentials credentials) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\Protocol\TableOperationHttpRequestFactory.cs:line 112
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass57_0.<InsertImpl>b__0(RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\TableOperation.cs:line 113
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 91
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 124
Request Information
RequestID:
RequestDate:
StatusMessage:
}

**Comment by kfarmer-msft** [comment]
Thank you -- we're looking into this.  To verify, can you describe the entity types in your case?

**Comment by dlmelendez** [comment]
Sure. Everything for a repro is in [https://github.com/dlmelendez/identityazuretable ](url).
Entities: 
[https://github.com/dlmelendez/identityazuretable/blob/master/src/ElCamino.AspNetCore.Identity.AzureTable/Model/IdentityUser.cs](url)
[https://github.com/dlmelendez/identityazuretable/blob/master/tests/ElCamino.AspNet.Identity.AzureTable.Tests/ModelTests/ApplicationUser.cs](url)
ApplicationUser inherits IdentityUser.

The easiest repro would be to pull down the identityazuretable code and open the /ElCamino.AspNetCore.Identity.AzureTable.sln in VS2015, make sure the 2.9 Azure Storage Emulator is running.
Execute the tests in test manager, they will all pass. Now upgrade the storage lib to 7.2, dotnet restore, and you will see all the same failures including for test **AccessFailedCount**. Basically any test that tries to create an identityuser will fail with the exception _**Microsoft.WindowsAzure.Storage.StorageException: An item with the same key has already been added.**_
Thanks, Dave

**Comment by erezvani1529** [comment]
Hi @dlmelendez ,

Thanks again for reporting this and providing the details. We are working on a fix for it already to handle the overridden members properly.

 To answer you question earlier:
> Why did you use GetAllProperties() instead of entity.GetType().GetTypeInfo().GetProperties(); as suggested?

In 7.1.3-preview, we were targeting netstandard1.6 TFM thus we could leverage from the initially proposed GetProperties() method in TypeInfo class. However, in 7.2.0 release we moved our target to netstandard1.3 to cover more platforms which does not support the GetProperties method. GetAllProperties() is an extension method added as a workaround.

**Comment by dlmelendez** [comment]
@erezvani1529 
Thanks for the explanation and for looking into this!

**Comment by dlmelendez** [comment]
@erezvani1529 @kfarmer-msft any update on this issue? I sure would like to be able to move my project https://github.com/dlmelendez/identityazuretable/ (.NET core assemblies) off of 7.1.3-preview. 7.2.1 current release still repros this issue. Thanks!

**Comment by erezvani1529** [comment]
Hi @dlmelendez,

7.2.1 was a hotfix release. This fix will be checked in to our dev branch and released with our v8.0  package. We will notify this thread as soon as the fix is checked in soon.

Thanks!

**Comment by erezvani1529** [comment]
Hi @dlmelendez,

This fix for this issue is included in the latest published package on nuget [v8.0.0](https://www.nuget.org/packages/WindowsAzure.Storage/) .


Thanks!
