### ISSUE TITLE
Table Storage - Inserting Entity Row Key with "/" character fails

### ISSUE THREAD

**Issue by 4eyecoder** [Azure/azure-storage-net#386]
If the row key contains the "/" character the exception below occurs in 8.0.0.0

It occurs when doing a bulk operation on table storage.  I am doing a InsertOrReplace.  

If I replace with the slash with a letter everything works fine.

Microsoft.WindowsAzure.Storage.StorageException: Element 0 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.ExecuteBatch(TableBatchOperation batch, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 165
   at EventHubToTableStorageWorker.LogEventProcessor.<Microsoft-ServiceBus-Messaging-IEventProcessor-ProcessEventsAsync>d__3.MoveNext() in C:\Data\LoggingCloudService\EventHubToTableStorageWorker\LogEventProcessor.cs:line 127
Request Information
RequestID:e7ec93dd-0002-0094-653e-67842a000000
RequestDate:Thu, 05 Jan 2017 10:28:54 GMT
StatusMessage:0:Bad Request - Error in query syntax.
ErrorCode:InvalidInput
ErrorMessage:0:Bad Request - Error in query syntax.
RequestId:e7ec93dd-0002-0094-653e-67842a000000
Time:2017-01-05T10:28:54.8692823Z

**Comment by 4eyecoder** [comment]
I just stumbled on an article that says that the "/" is not permitted in the row key

https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/understanding-the-table-service-data-model

**Comment by scovetta** [comment]
I'd like to request this issue be re-opened. Unless you happen to read that document, you get a "Bad Request - Error in query syntax." coming back as an exception, with nothing to go on to know that the RowKey value wasn't allowed. 

Could validation of RowKey be added to this library?

**Comment by thomaseyde** [comment]
Yes, please!

> Could validation of RowKey be added to this library?

When `PartitionKey` and `RowKey` are modelled as `string`, which can hold almost everything, and it's known that only a subset of strings are valid keys, then validation is in its place.

The service in itself could also send a hint of what's wrong, because `Error in query syntax` is a very strange error on an insert/replace action.
