### ISSUE TITLE
Problem running .net core 1.1 code that reads Blobs from Azure Storage in Azure App Service

### ISSUE THREAD

**Issue by johnkwaters** [Azure/azure-storage-net#413]
I have some code the runs fine in VS 2015, but when I deploy i to an Azure App Service, the service fails to start, with an internal error. 
The log contains:

2017-02-18T23:27:29
System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified. Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---

The code is as follows (credentials redacted)

using System.IO;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;

namespace xxx
{
    public class AzureProvider
    {
        public class AzureBlobModel
        {
            public string FileName { get; set; }
            public long? FileSize { get; set; }
            public Stream Stream { get; set; }
            public string ContentType { get; set; }
        }

        public async Task<AzureBlobModel> GetAzureBlob(string containerName, string fileName)
        {
            var cloudBlockBlob = ResolveCloudBlockBlob(containerName, fileName);
            var stream = await cloudBlockBlob.OpenReadAsync();

            var blob = new AzureBlobModel
            {
                FileName = fileName,
                FileSize = cloudBlockBlob.Properties.Length,
                Stream = stream,
                ContentType = cloudBlockBlob.Properties.ContentType
            };

            return blob;
        }

        public async Task<string> UploadStreamToAzure(string containerName, string fileName, MemoryStream stream)
        {
            var blockBlob = ResolveCloudBlockBlob(containerName, fileName);
            await blockBlob.UploadFromStreamAsync(stream);
            return fileName;
        }

        public CloudBlockBlob ResolveCloudBlockBlob(string containerName, string fileName)
        {
            var container = ResolveCloudBlobContainer(containerName);
            var blockBlob = container.GetBlockBlobReference(fileName);
            return blockBlob;
        }

        public CloudBlobContainer ResolveCloudBlobContainer(string containerName)
        {
            var storageAccount = GetCloudStorageAccount();
            var blobClient = storageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference(containerName);
            return container;
        }

        const string accountName = "xxx";
        const string accessKey = "xxx==";

        private CloudStorageAccount GetCloudStorageAccount()
        {
            //return CloudStorageAccount.Parse(ResolveAzureStorageConnectionString());
            return new CloudStorageAccount(
                new StorageCredentials(accountName, accessKey), true);
        }

        public string ResolveAzureStorageConnectionString()
        {
            return $"DefaultEndpointsProtocol=https;AccountName={accountName};AccountKey={accessKey}";
        }
    }
}

My project.json is

{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet-Tailspin.Surveys.WebAPI-54d0173b-2aba-481b-a341-6fa806cfad29",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Tailspin.Surveys.Data": "1.0.0-*",
    "Tailspin.Surveys.Common": "1.0.0-*",
    "Tailspin.Surveys.Security": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.Binder": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.13.8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
    "Microsoft.Extensions.Configuration": "1.1.0",
    "WindowsAzure.Storage": "8.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

I tried to do Add Connected Service, Azure Storage, see attached image

Help?
![addconnectedserviceerror](https://cloud.githubusercontent.com/assets/3422637/23097903/579448a2-f5f5-11e6-920e-1c4ad0c7d6a0.png)

**Comment by mirobers** [comment]
The error you see in the logs should be benign, perhaps indicating that diagnostics aren't enabled for your service. Do you have more information on the error that is preventing the service from starting? Does your code above run or does the failure happen earlier?

**Comment by johnkwaters** [comment]
I statred looking into it because when I deployed my service with this change (the class above, and the nuget package for WindowsAzure.Storage, the app will not launch:


An error occurred while starting the application.

.NET Core X86 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752    |    Microsoft Windows 6.2.9200    |   Need help?

**Comment by johnkwaters** [comment]
Here is my diagnostics file:

2017-02-19 18:59:29.399 +00:00 [Fatal] Application startup exception
System.TypeLoadException: Could not load type 'System.IO.File' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at Microsoft.Extensions.DependencyModel.FileWrapper.OpenRead(String path)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadEntryAssemblyContext(IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Tailspin.Surveys.WebAPI.Startup.ConfigureServices(IServiceCollection services) in C:\Users\John\Source\Repos\multitenant-saas-guidance-master\src\Tailspin.Surveys.WebAPI\Startup.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2017-02-19 18:59:29.599 +00:00 [Warning] Unable to bind to http://localhost:24001 on the IPv6 loopback interface.
System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)<---

2017-02-19 18:59:29.883 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/  
2017-02-19 18:59:29.957 +00:00 [Information] Request finished in 89.3042ms 500 text/html; charset=utf-8
2017-02-19 18:59:30.588 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/favicon.ico  
2017-02-19 18:59:30.588 +00:00 [Information] Request finished in 0.6176ms 500 text/html; charset=utf-8
2017-02-19 19:00:21.704 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/surveys/published  
2017-02-19 19:00:21.704 +00:00 [Information] Request finished in 0.4506ms 500 text/html; charset=utf-8
2017-02-19 19:00:21.897 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/favicon.ico  
2017-02-19 19:00:21.897 +00:00 [Information] Request finished in 0.4024ms 500 text/html; charset=utf-8
2017-02-19 19:08:20.457 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/surveys/published  
2017-02-19 19:08:20.457 +00:00 [Information] Request finished in 0.8261ms 500 text/html; charset=utf-8
2017-02-19 19:08:20.840 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/favicon.ico  
2017-02-19 19:08:20.840 +00:00 [Information] Request finished in 0.4287ms 500 text/html; charset=utf-8
2017-02-19 19:13:59.540 +00:00 [Fatal] Application startup exception
System.TypeLoadException: Could not load type 'System.IO.File' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at Microsoft.Extensions.DependencyModel.FileWrapper.OpenRead(String path)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadEntryAssemblyContext(IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Tailspin.Surveys.WebAPI.Startup.ConfigureServices(IServiceCollection services) in C:\Users\John\Source\Repos\multitenant-saas-guidance-master\src\Tailspin.Surveys.WebAPI\Startup.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2017-02-19 19:13:59.917 +00:00 [Warning] Unable to bind to http://localhost:26848 on the IPv6 loopback interface.
System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)<---

2017-02-19 19:14:00.158 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/surveys/published  
2017-02-19 19:14:00.199 +00:00 [Information] Request finished in 41.6339ms 500 text/html; charset=utf-8
2017-02-19 19:14:00.775 +00:00 [Information] Request starting HTTP/1.1 GET http://jmmtpocapi.azurewebsites.net/favicon.ico  
2017-02-19 19:14:00.775 +00:00 [Information] Request finished in 0.7303ms 500 text/html; charset=utf-8

**Comment by johnkwaters** [comment]
I manually deleted all the files from wwwrooot on Azure, redeployed, and now it is working...
