### ISSUE TITLE
Always invalid access signature

### ISSUE THREAD

**Issue by erwinwildenburg** [Azure/azure-storage-net#447]
I always get the following exception:
```
Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass27_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Blob\CloudBlockBlob.cs:line 293
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PullServer.Providers.AzureDscHandler.<SendReportAsync>d__37.MoveNext() in C:\Users\ErwinWildenburg\Source\Repos\PowerShell DSC Cloud\src\PullServer\Providers\Dsc\AzureDscHandler.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PullServer.Controllers.SendReportController.<PostAsync>d__2.MoveNext() in C:\Users\ErwinWildenburg\Source\Repos\PowerShell DSC Cloud\src\PullServer\Controllers\SendReportController.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Request Information
RequestID:f352c5d7-0001-004e-5de4-c5d0e2000000
RequestDate:Fri, 05 May 2017 23:16:44 GMT
StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ErrorCode:AuthenticationFailed
ErrorMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:f352c5d7-0001-004e-5de4-c5d0e2000000
Time:2017-05-05T21:16:31.7830178Z
```

It refuses the following piece of code:
`            CloudBlockBlob additionalData = _reportStatusDataContainer.GetBlockBlobReference(reserved.DeviceId + ".txt");
            await additionalData.UploadTextAsync(string.Join("\n\n", reserved.Body.StatusData));`

I build the clients as follows:
```
            _storageAccount = CloudStorageAccount.Parse(DefaultStorageConnection);
            _blobClient = _storageAccount.CreateCloudBlobClient();
            _tableClient = _storageAccount.CreateCloudTableClient();
            _reportTable = _tableClient.GetTableReference(ReportTableName);
            _reportStatusDataContainer =
 _blobClient.GetContainerReference(ReportStatusDataContainerName);
```

My connection string looks like this:
`DefaultEndpointsProtocol=https;AccountName=psdsccstorage;AccountKey=CENSORED;EndpointSuffix=core.windows.net`

For some reason the following part does work, which makes me think my code is correct...?:
```
            TableOperation insertOperation = TableOperation.InsertOrReplace(report);
            await _reportTable.ExecuteAsync(insertOperation);
```

**Comment by erwinwildenburg** [comment]
Damn... Turns out it was Application Insights...
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/416

Closing this...
