### ISSUE TITLE
CloudFile.OpenRead / OpenReadAsync fail with HTTP Conditional Header error

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-net#462]
Note:  Both `CloudFile.DownloadText()` and `CloudFile.DownloadToStream()` work normally . This is specific to `OpenRead` and `OpenReadAsync`

Attempts to use OpenRead and to then Read Results in `The condition specified using HTTP conditional header(s) is not met.`

            var _connectionStr = "DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY";
            var _azure_files_share_name = "share";
            var file = "file.txt";

            var fileClient = CloudStorageAccount.Parse(_connectionStr).CreateCloudFileClient();
            var libraryFilesStorageShare = fileClient.GetShareReference(_azure_files_share_name);
            var fileShare = libraryFilesStorageShare.GetRootDirectoryReference();

            var files = fileShare.ListFilesAndDirectories();
            var fileRef = fileShare.GetFileReference(notebook)

            var line = new StreamReader(fileRef.OpenRead()).ReadLine();

This fails with the following exception:
Microsoft.WindowsAzure.Storage.StorageException was unhandled
  HResult=-2146233088
  Message=The condition specified using HTTP conditional header(s) is not met.
  Source=Microsoft.WindowsAzure.Storage
  StackTrace:
       at Microsoft.WindowsAzure.Storage.File.FileReadStream.DispatchReadSync(Byte[] buffer, Int32 offset, Int32 count) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\FileReadStream.cs:line 265
       at Microsoft.WindowsAzure.Storage.File.FileReadStream.Read(Byte[] buffer, Int32 offset, Int32 count) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\FileReadStream.cs:line 79
       at System.IO.StreamReader.ReadBuffer()
       at System.IO.StreamReader.ReadLine()
       at TestingAzureFiles.Program.Main(String[] args) in C:\Users\crwilcox\Documents\Visual Studio 2015\Projects\TestingAzureFiles\TestingAzureFiles\Program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by pemari-msft** [comment]
`OpenRead` will lock on the Etag of the blob to make sure there's no concurrent writes to the blob as you're reading. This is so you don't see an inconsistent state of the blob. Are you running puts to the blob in parallel?

**Comment by crwilcox** [comment]
We aren't doing any parallel actions to my knowledge. This occurred while testing and repro'd in a small c# app against a file share. It seems using DownloadToStream works so that is what I do now.
