### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.8.1.0

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-storage-net#486]
I'm facing a very strange behaviour with VS 2017. I'm coding a new project that will use WindowsAzure.Storage library (8.1.4). After installing it and trying to run, it's throwing an exception:

_> 
> Microsoft.WindowsAzure.Storage.StorageException: 'Could not load file or assembly 'Microsoft.Data.OData, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
> 
> 
> FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified._

The strange part is that WindowsAzure.Storage has references to Microsoft.Data.OData 5.8.2. I can't figure out why it's searching for an old version. I also tried to installed and old version of WindowsAzure.Storage (8.0.0), but it also searches for a previous version of the Microsoft.Data.OData assembly. Any tips?

**Comment by thdotnet** [comment]
Here's the stack trace:

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 632
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableOperation.cs:line 44
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Create(TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 1084
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExists(TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 1211
   at Winter.Api.Services.AzureStorageService.SaveClient(Account model) in C:\Users\thiagoc\documents\visual studio 2017\Projects\Winter.Api\Winter.Api\Services\AzureStorageService.cs:line 46
   at Winter.Api.Controllers.AccountController.New(Account account) in C:\Users\thiagoc\documents\visual studio 2017\Projects\Winter.Api\Winter.Api\Controllers\AccountController.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by carl-ashby-silvertech** [comment]
@thdotnet  Hi, i see you closed this, did you figure out what the root cause was? 

Thanks.

**Comment by thdotnet** [comment]
Not really...but I can`t remember what I was doing on that time..

**Comment by erezvani1529** [comment]
@carl-ashby-silvertech,

Please try using binding redirects noting that the OData assembly version is 8.1.0 while the package is versioned 8.2 (since there was only a packaging change and no binary update in their latest release).

Thanks,
Elham

**Comment by 2moveit** [comment]
I just got the same error with 5.8.3. I'm using binding redirects to 5.8.3 so I wondered why that failed telling me something about 5.8.1. 
Solution: cleaning up the bin and obj folders

**Comment by gopimails** [comment]
I got the same error with 5.8.3. And WindowsAzure.Storage has references to Microsoft.Data.OData 5.8.2.
Cleaning up of bin/obj did not solve the issue. 
Downgraded 5.8.3 to 5.8.2 solved the issue for me.

**Comment by bluebirdtech** [comment]
Wow thanks @gopimails I was really stuck on that - the 5.8.2 workaround worked for me.

**Comment by MeganStyles** [comment]
Cleaning up bin and object folders worked for me too. Thanks!
