### ISSUE TITLE
Arabic character block causes 400 error

### ISSUE THREAD

**Issue by mooman219** [Azure/azure-storage-net#515]
WindowsAzure.Storage: `8.2.1`
.NET Framework: `4.6.1`
Language Level: `C# 7.0`

Not sure where else to report this. For Azure Table Storage, if you insert an entity with text matching this regex `[\u0640-\u064f/]` in the partition key, row key, or in the entity, the server will return a 400 error. That's a forward slash and part of the Arabic code block. Other Arabic characters work. 

Here's an example of what the error looks like:
```
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: Element 2 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndExecuteBatch(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 208
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ContentInsightBackend.Whitelist.AzureHandleProvider.<Update>d__7.MoveNext() in C:\Users\t-jocum\Source\Repos\MSN.Library.Social\OxfordBlue\ContentInsightBackend\Whitelist\AzureHandleProvider.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ContentInsightBackend.Program.LoadEntitiesDirect(String path, AzureHandleProvider azure) in C:\Users\t-jocum\Source\Repos\MSN.Library.Social\OxfordBlue\ContentInsightBackend\Program.cs:line 32
   at ContentInsightBackend.Program.Main() in C:\Users\t-jocum\Source\Repos\MSN.Library.Social\OxfordBlue\ContentInsightBackend\Program.cs:line 13
```

**Comment by erezvani1529** [comment]
Hi @mooman219,

As described in our [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN), the forward slash is not allowed, however there should not be any problems with the Arabic characters. Please avoid using the forward slash as Partition/Row key or in the EntityProperty value. Please re-open this issue if you have any other issues with this regard.

Thanks,
Elham
