### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native' in .NET Core 2.0 Console

### ISSUE THREAD

**Issue by lurumad** [Azure/azure-storage-net#530]
Hi,

I'm creating a .NET Core 2.0 console application and I'm trying to deploy in my Azure Batch account in Ubuntu 16.04 LTS node.

I'm using these packages:

```xml
<ItemGroup>
    <PackageReference Include="Azure.Batch" Version="7.1.0" />
    <PackageReference Include="Microsoft.Azure.Storage.DataMovement" Version="0.6.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="8.4.0" />
</ItemGroup>
```

When my process is finishing and I try to upload files to my storage account I'm receiving this weird error:

```json

Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'System.Net.Http.CurlHandler' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.WindowsAzure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpClientFactory.<>c.<.cctor>b__3_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass28_0.<<UploadFromStreamAsyncHelper>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass31_0.<<UploadFromFileAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProjectX.Administration.AzureBatch.Core.Krpano.Program.<UploadFileToContainer>d__5.MoveNext() in C:\dev\ProjectX\src\Administration\ProjectX.Administration.AzureBatch.Core.Krpano\Program.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProjectX.Administration.AzureBatch.Core.Krpano.Program.<RunProcessAsync>d__4.MoveNext() in C:\dev\ProjectX\src\Administration\ProjectX.Administration.AzureBatch.Core.Krpano\Program.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProjectX.Administration.AzureBatch.Core.Krpano.Program.<MainAsync>d__3.MoveNext() in C:\dev\ProjectX\src\Administration\ProjectX.Administration.AzureBatch.Core.Krpano\Program.cs:line 50
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ProjectX.Administration.AzureBatch.Core.Krpano.Program.Main(String[] args) in C:\dev\ProjectX\src\Administration\ProjectX.Administration.AzureBatch.Core.Krpano\Program.cs:line 22
Aborted (core dumped)
```

I don't know if is a problem related with Azure Storage SDK or .NET Core 2.0 (Core Fx) running in Linux.

If you need more info, please tell me.

Regards.

**Comment by lurumad** [comment]
Fix the error, I forgot install the prereqs 

https://github.com/dotnet/core/blob/master/Documentation/prereqs.md

Regards!
