### ISSUE TITLE
CloudStorageAccount.Parse throwing false pozitive exception

### ISSUE THREAD

**Issue by john-32767** [Azure/azure-storage-net#536]
By using the following connection string example, we get the below error:

connectionString="DefaultEndpointsProtocol=https;AccountName=accountName;AccountKey=askdhaskjdhasIYIUYIUYIHKJHASDKHkhkjhkj=="

The account key contains "==" and so the parser cannot deal with it.

```
2017-09-13 09:42:29.2517 - ERROR - System.FormatException: Settings must be of the form "name=value".
at Microsoft.WindowsAzure.Storage.CloudStorageAccount.b__0(String err) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs:line 525
at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseStringIntoSettings(String connectionString, Action`1 error) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs:line 987
at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseImpl(String connectionString, CloudStorageAccount& accountInformation, Action`1 error) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs:line 807
at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs:line 525
```

**Comment by erezvani1529** [comment]
Hi @john-32767,

Thanks for reporting your issue. Would you please provide a simple repro-code? We are not able to repro with our tests or the string that you have provided here. Also given the stack trace I am assuming you are using version 8.4. Would you please confirm and update with the target framework of your application?

Thanks,
Elham

**Comment by erezvani1529** [comment]
@john-32767 , closing this issue since we did not receive any more information from you. Please do not hesitate to bring up if you see any other issues.

Thanks,
Elham
