### ISSUE TITLE
StorageServiceClient._normalizeError

### ISSUE THREAD

**Issue by ferrantejake** [Azure/azure-storage-net#575]
I am working with the Tables services and occasionally, without consistency, I am getting this error.

**Under what circumstances the issue appears**
This error occurs without any obvious cause during the run-time of my application. There is no obvious time interval or series of events that occur which leads up to this - the app can sit idly and it will happen every so often. I don't even need to be actively using the module. One of the first thing my app does when it starts up is create tables but doesn't get further than that before I see this error sometimes.
  
**What is the impact**
Seemingly no side effects

```
uncaught exception Error
    at Function.StorageServiceClient._normalizeError (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1045:23)
    at BatchResult._parseOperation (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:214:51)
    at /home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:162:29
    at Array.forEach (<anonymous>)
    at BatchResult.parse (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/models/batchresult.js:155:18)
    at processResponseCallback (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/services/table/tableservice.js:1147:39)
    at Request.processResponseCallback [as _callback] (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/lib/common/services/storageserviceclient.js:303:13)
    at Request.self.callback (/home/jakef/Documents/Code/Droplit/droplit.io-services/projects/@droplit/dq/node_modules/azure-storage/node_modules/request/request.js:199:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7) +17m
```

**Comment by erezvani1529** [comment]
Hi @ferrantejake,

Would you please open this issue in Azure Storage Client for [Node.js github](https://github.com/Azure/azure-storage-node) repository? This the .Net client repo :)

Thanks,
Elham
