### ISSUE TITLE
Unable to create queues on Azure Stack

### ISSUE THREAD

**Issue by charliejllewellyn** [Azure/azure-storage-net#591]
I have some very simple code to create a queue on Azure Stack. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;
using Microsoft.Azure; // Namespace for CloudConfigurationManager
using Microsoft.WindowsAzure.Storage; // Namespace for CloudStorageAccount
using Microsoft.WindowsAzure.Storage.Queue; // Namespace for Queue storage types

namespace azurestack
{
    class Program
    {
        static void Main(string[] args)
        {
            //Console.Write(ConfigurationManager.AppSettings.Get("StorageConnectionString"));
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
               CloudConfigurationManager.GetSetting("StorageConnectionString"));
            CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
            CloudQueue queue = queueClient.GetQueueReference("myqueue");
            queue.Create();
        }
    }
}
```

app.config has 

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
  <appSettings>
    <add key="StorageConnectionString" value="DefaultEndpointsProtocol=https;AccountName=testaccount002;AccountKey=iVtx5TePJg+72Q/wQ/z73cV4tpw+U5j8ZEC5cjlWa5pcc3VXJFBaDtKkKSttpkIXhJENrlBi58Nr9js1hivQYQ==;EndpointSuffix=local.azurestack.external" />
  </appSettings>
</configuration>
```

I get the error:

```
Microsoft.WindowsAzure.Storage.StorageException
  HResult=0x80131500
  Message=The remote server returned an error: (400) Bad Request.
  Source=Microsoft.WindowsAzure.Storage
  StackTrace:
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.Create(QueueRequestOptions options, OperationContext operationContext)
   at azurestack.Program.Main(String[] args) in C:\Users\AzureStackAdmin\source\repos\azurestack\azurestack\Program.cs:line 22

Inner Exception 1:
WebException: The remote server returned an error: (400) Bad Request.
```

The code however works correctly against Azure.

**Comment by mirobers** [comment]
The [Azure Stack docs](https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-acs-differences) indicate that storage service version 2015-04-05 is supported. This means you will need to use version 6.2.0 of this library to be compatible with Azure Stack.
