### ISSUE TITLE
Difference between requests coming from net461 and netcoreapp2.0 causes runtime error with CosmosDB Table Api

### ISSUE THREAD

**Issue by johlrich** [Azure/azure-storage-net#601]
If you use ExecuteQuerySegmentedAsync with a netcoreapp2.0 you will get a runtime exception saying the response is missing the `odata.metadata` property. This does not occur on net461. 

When looking at the requests generated from each, there is a difference of a space:
net461 build sends an accept header of `application/json;odata=minimalmetadata` 
netcoreapp2.0 build sends an accept header of `application/json; odata=minimalmetadata`.

This space causes the cosmos table api to not return the odata.metadata property and instead embeds the metadata in each object.
net461 response has `Content-Type: application/json;odata=minimalmetadata`
netcoreapp2.0 response has `Content-Type: application/json`

Stack trace of exception:
```
Microsoft.Data.OData.ODataException : The required instance annotation 'odata.metadata' was not found at the beginning of a response payload.
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ReadMetadataUriAnnotation(ODataPayloadKind payloadKind, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Boolean failOnMissingMetadataUriAnnotation)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStartImplementation(ODataPayloadKind payloadKind, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.ReadSynchronously()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.Data.OData.ODataReaderCore.Read()
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.<>c__DisplayClass3_0`1.<TableQueryPostProcessGeneric>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass24_0`2.<<QueryImpl>b__2>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
```

**Comment by northtyphoon** [comment]
Hit the same issue in v8.7.0 (.net core 2.0 app)

**Comment by johlrich** [comment]
@northtyphoon I had also sent a link to this issue to the cosmos team and got a reply from them earlier today saying they have a fix that will be rolled out in a few weeks. They said they could possibly escalate if it's a major blocker, but I didn't take them up on that offer (couple weeks is fine for me). If you're seriously blocked you could try reaching out to them as well.

I'll circle back and close this issue once that happens.

**Comment by erezvani1529** [comment]
cc: @ausfeldt from CosmosDB sdk team.

Garrett, would you please update the status of the issue once the fix is out?

Thanks!

**Comment by deepakyadav** [comment]
The fix was rolled out long ago in January. Thanks @johlrich for reporting.

**Comment by erezvani1529** [comment]
Closing this issue as fixed by CosmosDB team.

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information. 

Thanks!
