### ISSUE TITLE
StorageException: The argument is out of range. CloudBlockBlob.CreateSnapshot()

### ISSUE THREAD

**Issue by That-User** [Azure/azure-storage-net#608]
Below is the method I've made to create a snapshot for all blobs in a container:

    public static EmsStorageSnapshot CreateSnapshot(EmsStorageAccount storageAccount, EmsStorageContainer nContainer)
    {
      try
      {
        DateTime snapDate = DateTime.Now;

        EmsStorageSnapshot snapshot = new EmsStorageSnapshot() { CreatedAt = snapDate, SnapshotReference = snapDate.ToString() };
        // var metadata = new Dictionary<string, string> { { "snapshotIssued", snapDate.ToString() } };

        CloudStorageAccount account = new CloudStorageAccount(new StorageCredentials(storageAccount.StorageAccountName, storageAccount.StorageAccountKey), false);
        
        var client = account.CreateCloudBlobClient();
        var container = client.GetContainerReference(nContainer.ContainerName);

        List<CloudBlockBlob> blobs = container.ListBlobs().OfType<CloudBlockBlob>().ToList();

        foreach (var blob in blobs)
        {
          try
          {
            if (!blob.IsSnapshot)
            {
              var snapBlob = blob.CreateSnapshot();
              snapBlob.Metadata.Add("snapshotIssued", snapDate.ToString());
              snapBlob.SetMetadata();
            }
          }
          catch (StorageException ex)
          {
            Console.WriteLine("Failed to create a snapshot of blob {0}.", blob.Name);
            Logger.Log("Failed to create a snapshot of blob '" + blob.Name + "': " + ex.ToString(), VerboseLevel.Error);
          }
        }
        return snapshot;
      }
      catch (Exception ex)
      {
        Logger.Log(ex.ToString(), VerboseLevel.Error);
      }
      return null;
    }

At the line ( var snapBlob = blob.CreateSnapshot(); ) i get the following error:

    Microsoft.WindowsAzure.Storage.StorageException: The argument is out of range. Value passed: 
    Parameter name: snapshot ---> System.ArgumentOutOfRangeException: The argument is out of range. Value passed: 
    Parameter name: snapshot
       at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.ArgumentOutOfRange(String paramName, Object value) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\CommonUtility.cs:line 168
       at Microsoft.WindowsAzure.Storage.Core.Util.NavigationHelper.ParseSnapshotTime(String snapshot) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\NavigationHelper.cs:line 665
       at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass69.<CreateSnapshotImpl>b__68(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 3006
       at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 711
   
Am i doing something wrong or is this a bug?

Microsoft.WindowsAzure.Storage.dll version = 8.7.0.0

**Comment by erezvani1529** [comment]
Hi @That-User,

The only issue I see here is that your code is trying to set metadata on a blob snapshot which is not allowed. Is that possible for you to share a fiddler trace with us to see what response is coming back from server?  (particularly interested in the `"x-ms-snapshot"` response header  )(`ascl at Microsoft dot com`)

Thanks!

**Comment by erezvani1529** [comment]
Hi @That-User,

Closing since we did not hear back. Please do not hesitate to re-open this issue if you still need assistance or have any other related question.

Thanks!
