### ISSUE TITLE
HttpRequestMessageFactory.CreateRequestMessage, timeout already set within builder causing ArgumentException

### ISSUE THREAD

**Issue by RikvanDoorn** [Azure/azure-storage-net#620]
I'm suspecting this has something to do with retrying, since it usually happens after 1/2 activations of the (exponential) retry policy after timeout. It appears the "timeout" key within the UriQueryBuilder is already set, and the method tries to add it as well without proper check, causing an exception.

Exception:
`[02/05/2018 18:30:41 > 171692: INFO] Application startup exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (An item with the same key has already been added. Key: timeout)) ---> System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: timeout) ---> Microsoft.WindowsAzure.Storage.StorageException: An item with the same key has already been added. Key: timeout ---> System.ArgumentException: An item with the same key has already been added. Key: timeout
[02/05/2018 18:30:41 > 171692: INFO]    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder.Add(String name, String value)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.CreateRequestMessage(HttpMethod method, Uri uri, Nullable`1 timeout, UriQueryBuilder builder, HttpContent content, OperationContext operationContext, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestCore(Uri uri, UriQueryBuilder builder, HttpMethod method, Nullable`1 timeout, HttpContent content, OperationContext ctx, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableQuery(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, HttpContent content, OperationContext ctx, TablePayloadFormat payloadFormat, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass24_0`2.<QueryImpl>b__0(RESTCommand`1 cmd, Uri uri, UriQueryBuilder queryBuilder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO]    --- End of inner exception stack trace ---
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass20_0.<<ExecuteQuerySegmentedAsync>b__0>d.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    --- End of inner exception stack trace ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    --- End of inner exception stack trace ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[02/05/2018 18:30:41 > 171692: INFO] ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: timeout) ---> Microsoft.WindowsAzure.Storage.StorageException: An item with the same key has already been added. Key: timeout ---> System.ArgumentException: An item with the same key has already been added. Key: timeout
[02/05/2018 18:30:41 > 171692: INFO]    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder.Add(String name, String value)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.CreateRequestMessage(HttpMethod method, Uri uri, Nullable`1 timeout, UriQueryBuilder builder, HttpContent content, OperationContext operationContext, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestCore(Uri uri, UriQueryBuilder builder, HttpMethod method, Nullable`1 timeout, HttpContent content, OperationContext ctx, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableQuery(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, HttpContent content, OperationContext ctx, TablePayloadFormat payloadFormat, ICanonicalizer canonicalizer, StorageCredentials credentials)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass24_0`2.<QueryImpl>b__0(RESTCommand`1 cmd, Uri uri, UriQueryBuilder queryBuilder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO]    --- End of inner exception stack trace ---
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass20_0.<<ExecuteQuerySegmentedAsync>b__0>d.MoveNext()
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    --- End of inner exception stack trace ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
[02/05/2018 18:30:41 > 171692: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/05/2018 18:30:41 > 171692: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by RikvanDoorn** [comment]
[exception.txt](https://github.com/Azure/azure-storage-net/files/1698564/exception.txt)

**Comment by RikvanDoorn** [comment]
My proposed fix is adding a check to check whether or not the key already exists within the builder. If it does already exist, either add a setter to the this[] of the builer, or just use the currently set value and ignore the new value.

Also probably add the "timeout" string to the QueryConstants class, for good measure.

**Comment by erezvani1529** [comment]
@RikvanDoorn  thanks for reporting this issue. I will look into this issue and take a fix for our next release v9.1.

-Elham

**Comment by kristianhald** [comment]
I just debugged this, as we are having the same problem.
The problem happens, if you set 'TableRequestOptions.ServerTimeout' and a retry occurs.

To be more specific on line 91 in Executor.cs a call to 'cmd.BuildRequest' is made, which is inside a retry-while-loop. A new builder is created on line 90, but if you look at how the cmd.BuildRequest is setup, then this builder is not used (TableQueryGeneric.cs line 146):
```C#
queryCmd.BuildRequest = (cmd, uri, --->queryBuilder<---, cnt, serverTimeout, ctx) => TableOperationHttpRequestMessageFactory.BuildRequestForTableQuery(uri, --->builder<---, serverTimeout, cnt, ctx, requestOptions.PayloadFormat.Value, client.GetCanonicalizer(), client.Credentials);
```
The builder provided as a parameter 'queryBuilder' is not used, but instead a builder created during the QueryImpl method call is used (The 'builder' variable). It is this builder that is provided with 'timeout' twice, if a retry occurs in the executor.
