### ISSUE TITLE
TableEntity.Flatten doesn't support complex objects with collections

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [Azure/azure-storage-net#672]
It looks like TableEntity.Flatten doesn't support complex objects collections. 
`WindowsAzure.Storage` in version 9.1.1. It looks similar to the https://github.com/Azure/azure-storage-net/issues/426

repro:
```csharp
        public static void Main()
        {
            var root = new Parent
            {
                Childrens = new[] { new Children { Name = "Łukasz" } }
            };

            TableEntity.Flatten(root, new OperationContext());
        }

        public class Parent
        {
            public Children[] Childrens { get; set; }
        }

        public class Children
        {
            public string Name { get; set; }
        }
```

exception:
```
Unhandled Exception: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.<>c__DisplayClass5_0.<Flatten>b__1(PropertyInfo propertyInfo) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\EntityPropertyConverter.cs:line 194
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.Flatten(Dictionary`2 propertyDictionary, Object current, String objectPath, HashSet`1 antecedents, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\EntityPropertyConverter.cs:line 184
   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.<>c__DisplayClass5_0.<Flatten>b__1(PropertyInfo propertyInfo) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\EntityPropertyConverter.cs:line 194
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.Flatten(Dictionary`2 propertyDictionary, Object current, String objectPath, HashSet`1 antecedents, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\EntityPropertyConverter.cs:line 184
   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.Flatten(Object root, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Table\EntityPropertyConverter.cs:line 75
   at ProjectForTests.Program.Main() in C:\dev\ProjectForTests\ProjectForTests\Program.cs:line 18
```

dotnet info:

> Product Information:
>  Version:            2.1.104
>  Commit SHA-1 hash:  48ec687460
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.104\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.6
>   Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by erezvani1529** [comment]
Hi,

Since the release of CosmosDB Table sdk [package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/), 
support for Table service has transitioned to CosmosDB team.

Please email the team at : `askcosmosdbtableapi@microsoft.com` for more information. 

Thanks!
