### ISSUE TITLE
Breaking blob lease results 409 conflict error (ErrorCode:LeaseNotPresentWithLeaseOperation)

### ISSUE THREAD

**Issue by stevenxi** [Azure/azure-storage-net#707]
The error throws when calling `Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.BreakLease();`

This error only happened ~~once~~ several times so far, unable to reproduce it.
But error doesn't quite make sense.

When trying to reproduce the error, it appears 'BreakLease()' regardless the lease status. So why would this error show up?

```
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Unicorn.Service.FileStorage.Implementation.CloudFile.BreakLease() in C:\BuildAgent\work\553cdece956e7c00\src\infrastructure\Unicorn\JobProcessor\Unicorn.Service.FileStorage\Implementation\CloudFile.cs:line 50

Request Information
RequestID:f6973da6-f01e-00c8-4704-fb8430000000
RequestDate:Sun, 03 Jun 2018 06:34:03 GMT
StatusMessage:There is currently no lease on the blob.
ErrorCode:LeaseNotPresentWithLeaseOperation
ErrorMessage:There is currently no lease on the blob.
RequestId:f6973da6-f01e-00c8-4704-fb8430000000
Time:2018-06-03T06:34:03.7116624Z

```

**Comment by mirobers** [comment]
This happens when attempting to break a lease on a blob that doesn't have a lease because either the lease was never acquired or it was released. You won't see this error when the blob has an expired or broken lease.

**Comment by stevenxi** [comment]
@mirobers Thanks! It's very helpful. Apparently all my attempts to reproducing were using files that with 'Broken' or 'Expired' leases.
