### ISSUE TITLE
Intermittent deadlock in CloudTable.ExecuteQuerySegmented

### ISSUE THREAD

**Issue by m-mertz** [Azure/azure-storage-net#714]
We’re intermittently running into a deadlock in CloudTable.ExecuteQuerySegmented. Our query is quite simple:

> TableQuery<TElement> query = new TableQuery<TElement>().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, partitionKey));
 
This happens about once per day, while this query gets called every 5 minutes on hundreds of machines. So quite rarely, relatively speaking. Going by a few dumps, it’s always hanging in the same place, in Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableQueryPostProcessGeneric. We’re on WindowsAzure.Storage 9.2.0.

I asked for help internally in Microsoft on this issue (I'm mamertz) and some .NET folks actually investigated the memory dump. They tracked down an HttpWebRequest object that is still active and might be blocking the code. Their follow-up questions:

> Can you give me some background on the code pattern that is used here in calling the System.Net APIs?  Specifically, I assume that HttpWebRequest is being used.  But are the API calls to HttpWebRequest being done with async APM pattern (BeginGetResponse/EndGetResponse) or async Task pattern (GetResponseAsync) or sync pattern (GetResponse)?  The dump file suggests “sync pattern”.

> And how is the cancellation logic done in your layer (if any)?  How/when do you call HttpWebRequest.Abort()? Are you combining sync pattern calls and Abort()?

They also pointed out some of the .GetAwaiter().GetResult() calls on async methods in the storage SDK as possible root cause, e.g. this one here in TableOperationHttpResponseParsers:
> ReadQueryResponseUsingJsonParserAsync(retSeg, responseStream, resp.Headers[Constants.HeaderConstants.EtagHeader], resolver, options.PropertyResolver, typeof(TQueryType), null, options, System.Threading.CancellationToken.None).GetAwaiter().GetResult();

**Comment by maksimkim** [comment]
We experience same issue starting from 9.0.

Small repro being run against slow table storage shows constant increase of threads in process
https://gist.github.com/maksimkim/e31427897b17970154f3d0e8d2c9f4cc

This doesn't repro on 7.X and 8.X

**Comment by hami89** [comment]
Have you tested it on v9.3? Is the issue still present?

**Comment by Prybe** [comment]
Same issue here for "ExecuteQuerySegmented". Also in v9.3.

Call:
..
var queryResult = await table.ExecuteQuerySegmentedAsync(new TableQuery<MyDto>(), token);

Exception:
`Microsoft.WindowsAzure.Storage.StorageException: Method not found: 'System.Threading.Tasks.Task`1<Newtonsoft.Json.Linq.JObject> Newtonsoft.Json.Linq.JObject.LoadAsync(Newtonsoft.Json.JsonReader, System.Threading.CancellationToken)'. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Newtonsoft.Json.Linq.JObject> Newtonsoft.Json.Linq.JObject.LoadAsync(Newtonsoft.Json.JsonReader, System.Threading.CancellationToken)'.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.<ReadQueryResponseUsingJsonParserMetadataAsync>d__1d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.ReadQueryResponseUsingJsonParserMetadataAsync(Stream responseStream, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableQueryPostProcessGeneric[TElement,TQueryType](Stream responseStream, Func`6 resolver, HttpWebResponse resp, TableRequestOptions options, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpResponseParsers.cs:line 329
   at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass10`2.<QueryImpl>b__f(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableQuery.cs:line 568
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessEndOfRequest[T](ExecutionState`1 executionState) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 898
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndOperation[T](ExecutionState`1 executionState) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 425
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndExecuteQuerySegmented[TResult](IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 646
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 69`

**Comment by psocha** [comment]
I ran into this issue (same stack trace as above) on v9.3.2.

There are ExecuteQuerySegmentedAsync() and EndExecuteQuerySegmented() calls in my codebase that return this StorageException consistently, not just intermittently as others have reported.

@m-mertz @maksimkim @hami89 @Prybe Anyone found a workaround or have any new knowledge to share?

**Comment by Prybe** [comment]
1) I use a retry strategy 
2) extend the monitoring and logging
But i didn´t see the issue anymore. weird but true. 
My plan is to create some tests where the size of the objects in the storage account are different. (currently more or less the same size).
So maybe it is related to that.

**Comment by psocha** [comment]
In my case, the problem was happening because I was using a .NET 4.0 Newtonsoft.Json.dll alongside a .NET 4.5 Microsoft.WindowsAzure.Storage.dll. The problem went away once I ensured both packages were on a .NET 4.5 version.

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)

**Comment by amrutasawant-gep** [comment]
> 1. I use a retry strategy
> 2. extend the monitoring and logging
>    But i didn´t see the issue anymore. weird but true.
>    My plan is to create some tests where the size of the objects in the storage account are different. (currently more or less the same size).
>    So maybe it is related to that.

Can you please share your retry values.
Refer my current code as below,

TableRequestOptions reqOptions = new TableRequestOptions()
{
         RetryPolicy = new LinearRetry(TimeSpan.FromSeconds(3), 3)
};

TableQuerySegment<T> tableQueryResult = await cloudTable.ExecuteQuerySegmentedAsync(tableQuery, entityResolver, continuationToken, reqOptions, null);
