### ISSUE TITLE
Unobserved exception was rethrown by the finalizer thread while using Storage Client

### ISSUE THREAD

**Issue by rduser** [Azure/azure-storage-net#722]
We are using the storage .Net SDK to interact with the blob service. We frequently see the following exception, across our Production data centers, being logged by the  TaskScheduler.UnobservedTaskException handler.

```
Type: System.AggregateException
Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
ToString: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\ByteCountingStream.cs:line 149
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\ByteCountingStream.cs:line 149
StackTrace: 
Type: System.ObjectDisposedException
Message: Cannot access a disposed object.
Object name: 'SslStream'.
ToString: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\ByteCountingStream.cs:line 149
StackTrace:    at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\ByteCountingStream.cs:line 149
```

All of our code uses the async methods and we await all of these appropriately (as I can tell)

1. How can we get rid of this exception? As you will notice we do not see any of our code in this stack?

**Comment by rduser** [comment]
Any update on this?
