### ISSUE TITLE
System.FormatException when trying to download blob with not en-us CultureInfo.CurrentCulture

### ISSUE THREAD

**Issue by emetsds** [Azure/azure-storage-net#723]
CloudBlobClient can`t parse DateTime when CultureInfo.CurrentCulture is not en-us.

Version:
.NET 4.7.2 
WindowsAzure.Storage 9.2.0

Code:
```csharp			
var client = CloudStorageAccount.Parse(connectionString);  
CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("th-th");  
using (var stream = new MemoryStream())  
    await client.CreateCloudBlobClient()  
        .GetContainerReference(_testFilesContainer)  
        .GetBlobReference(_preUploadBlobName)  
        .DownloadToStreamAsync(stream);  
```

Exception:
> Microsoft.WindowsAzure.Storage.StorageException : String was not recognized as a valid DateTime because the day of week was incorrect.
  ----> System.FormatException : String was not recognized as a valid DateTime because the day of week was incorrect.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
--FormatException
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at Microsoft.WindowsAzure.Storage.Blob.Protocol.BlobHttpResponseParsers.GetProperties(HttpWebResponse response)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.UpdateAfterFetchAttributes(BlobAttributes blobAttributes, HttpWebResponse response)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.<>c__DisplayClass1e.<GetBlobImpl>b__1b(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)

**Comment by zezha-msft** [comment]
Hi @emetsds, thanks for reaching out!

I've logged this issue for investigation.

**Comment by Jirapong** [comment]
@zezha-msft I can confirm this is the case. I'm also having a similar problem as code 

```
Thread.CurrentThread.CurrentCulture = new CultureInfo("th-TH");

CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationHelper.GetConfiguration("StorageConnectionString"));
CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
CloudBlobContainer container = blobClient.GetContainerReference(containerName);
CloudBlockBlob blockBlob = container.GetBlockBlobReference(blobPath);

// error happen here
blockBlob.Exists()

```
exception is

```
String was not recognized as a valid DateTime because the day of week was incorrect.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1106
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadToStream(Stream target, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 234
```

**Comment by sgryt** [comment]
I can confirm that the problem also exists for the following additional cultures ((3-letter ISO formatted): `ara, bas, dua`.

Do you have any suggestions for a workaround? This is a huge problem for ASP.NET MVC applications, where the users browser settings determines the culture that is being used to deserialize the `x-ms-creation-time` HTTP response header from the blob service.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
