### ISSUE TITLE
[v9.1.1] MaxExecutionTime is not always respected on UploadFromStreamAsync.

### ISSUE THREAD

**Issue by Yonisha** [Azure/azure-storage-net#729]
Got a case where UploadFromStreamAsync operation took 40 minutes although MaxExecutionTime is set with 2 minutes.
Looking at the storage logs, I haven't seen operation on that blob meaning that the request was tuck on the storage client.
Unfortunately I do not have more information to share. Is there any known issue with client version 9.1.1?

`Exception Microsoft.WindowsAzure.Storage.StorageException: Unable to read data from the transport connection: The connection was closed. ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsyncHelper>d__8.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsync>d__4.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 228
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadFromStream(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 846
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by zezha-msft** [comment]
Hi @Yonisha, thanks for reaching out!

I've logged this issue for investigation.

**Comment by Yonisha** [comment]
Thanks, note that I reverted to v9.0.0 and still encounter this issue.
Will try to provide a dump

**Comment by Yonisha** [comment]
Looks like related to Redis client [issue](https://github.com/StackExchange/StackExchange.Redis/issues/759) which causing thread pool exhaustion.

**Comment by Yonisha** [comment]
Hi,

Reverting the Redis configuration didn't help after all  - looks like the MaxExecutionTime is not respected after all.

All exceptions are either:

- 'System.IO.IOException: Unable to write data to the transport connection'
- 'System.IO.IOException: Unable to read data from the transport connection'

**Comment by Yonisha** [comment]
Another thing I've tried with no success is providing a cancellation token with configured timeout for UploadFromStreamAsync API.

```
CancellationTokenSource source = new CancellationTokenSource(TimeSpan.FromMinutes(2));
await blob.UploadFromStreamAsync(_stream, null, requestOptions, null, source.Token);
```

Any recommendation for a workaround?
