### ISSUE TITLE
Download with BeginRead in BlobReadStream retrieved from CloudBlockBlob will not retry

### ISSUE THREAD

**Issue by MSRY** [Azure/azure-storage-net#749]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
9.3

### Which platform are you using? (ex: .NET Core 2.1)
.Net Framework 4.6

### What problem was encountered?
When use BeginRead method in BlobReadStream and Network Error happened, the retry policy will not be used for retry.

### How can we reproduce the problem in the simplest way?
Below is your log when network error happens.
Starting operation with location Primary per location mode PrimaryOnly.
This operation can only be executed against the primary storage location.
Starting asynchronous request to https://xxx.table.core.windows.net/Audit()
Setting payload format for the request to 'Json'.
Preparing to write request data.
Processing response body.
Disposing action invoked.
Operation completed successfully.
Checking if the operation should be retried. Retry count = 0, HTTP status code = 306, Retryable exception = no, Exception = Index was out of range. Must be non-negative and less than the size of the collection.
Retry policy did not allow for a retry. Failing with Index was out of range. Must be non-negative and less than the size of the collection.
Disposing action invoked.
Disposing action invoked.
Disposing action threw an exception : Cryptographic error occurred. Please check the inner exception for more details.
Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsyncHelper>d__8.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsync>d__4.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 228
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Blob.BlobReadStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\BlobReadStream.cs:line 151
Exception thrown while retrying operation: Index was out of range. Must be non-negative and less than the size of the collection.
.Parameter name: index.
Operation completed successfully.

### Have you found a mitigation/solution?
Put retry policy during OpenRead method but not work.

**Comment by zezha-msft** [comment]
Hi @MSRY, thanks for reaching out!

I've logged this issue for investigation.

**Comment by zezha-msft** [comment]
@MSRY, are you sure that you specified the right range? The error was `Index was out of range` and that cannot be retried.

**Comment by seanmcc-msft** [comment]
Please reactivate if you are still experiencing this issue.
