### ISSUE TITLE
Buffer leak in CloudBlockBlob.UploadFromStream()

### ISSUE THREAD

**Issue by hans-olav** [Azure/azure-storage-net#766]
`CloudBlockBlob.UploadFromStream()` leaks buffers when using `IBufferManager` when the stream is not seek-able. Below [2] is a minimal repro, which prints what’s shown in [1] - ie. it leaks one buffer.
The stack of the buffer allocation that leaked can be seen in [3].

**[1] Output**
```
Take 21eb607
Take 3e0d77a
Return 3e0d77a
```

**[2] Minimal repro**
```
void Main()
{
    var client = CloudStorageAccount.Parse("UseDevelopmentStorage=true").CreateCloudBlobClient();
    client.BufferManager = new LoggingDummyBufferManager();

    var stream = new NonSeekableStream();
    stream.SetLength(1);

    var container = client.GetContainerReference("foo");
    container.CreateIfNotExists();

    var blob = container.GetBlockBlobReference("foo.txt");
    blob.UploadFromStream(stream);
}

class NonSeekableStream : MemoryStream
{
    public override bool CanSeek => false;
}

class LoggingDummyBufferManager : IBufferManager
{
    public int GetDefaultBufferSize() => 64 * 1024;

    public void ReturnBuffer(byte[] buffer) =>
        Console.WriteLine("Return {0:x}", buffer.GetHashCode());

    public byte[] TakeBuffer(int bufferSize)
    {
        var buffer = new byte[bufferSize];
        Console.WriteLine("Take {0:x}", buffer.GetHashCode());
        //Console.WriteLine(Environment.StackTrace);
        return buffer;
    }
}
```

**[3] Stack allocating the leaked buffer.**
```
Take 21eb607
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at UserQuery.LoggingDummyBufferManager.TakeBuffer(Int32 bufferSize)
   at Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.AddBlock() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\MultiBufferMemoryStream.cs:line 646
   at Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.Reserve(Int64 requiredSize) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\MultiBufferMemoryStream.cs:line 637
   at Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\MultiBufferMemoryStream.cs:line 302
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 165
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 125
   at Microsoft.WindowsAzure.Storage.Core.Util.StreamExtensions.WriteToSync[T](Stream stream, Stream toStream, Nullable`1 copyLength, Nullable`1 maxLength, Boolean calculateMd5, Boolean syncRead, ExecutionState`1 executionState, StreamDescriptor streamCopyState) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\StreamExtensions.cs:line 138
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 431
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStream(Stream source, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 310
   at UserQuery.Main()
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.StartQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.<>c__DisplayClass153_0.<ExecuteClrQuery>b__0()
   at LINQPad.ExecutionModel.Server.SingleThreadExecuter.Work()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ttrunck** [comment]
I can also repro with seekable stream. (For small files this isn't using any buffer but as soon as the file is big enough I'm hitting the same issue).
It looks like only the last buffer is returned.
