### ISSUE TITLE
Writing a blob to the Azure Storage Emulator version 5.8 Fails

### ISSUE THREAD

**Issue by dts-m** [Azure/azure-storage-net#801]
### Which service(blob, file, queue, table) does this issue concern?
Writing a blob to the Azure Storage Emulator version 5.8.

### Which version of the SDK was used?
9.1.1 & 9.3.2

### Which platform are you using? (ex: .NET Core 2.1)
Windows 10 1803 Pro, .NET Framework 4.6.1

### What problem was encountered?
When I try to write a blob using a [`MultipartFormDataStreamProvider`](https://docs.microsoft.com/en-us/previous-versions/aspnet/hh835949(v%3Dvs.118)), the SDK fails and returns a generic a 500 Internal Error response.

### How can we reproduce the problem in the simplest way?
As described, the write blob operation that I perform against the v5.8 emulator fails.
[I have attached sample logs(azure_storage_emulator_logs.zip)](https://github.com/Azure/azure-storage-net/files/2532018/azure_storage_emulator_logs.zip)

### Have you found a mitigation/solution?
If I use SDK 9.1.1 with Azure Storage Emulator 5.3, or SDK 9.3.2 with Azurite 2.6.7 or an actual azure storage endpoint, everything works.

**Comment by vovikdrg** [comment]
I do have same problem.
I have Azure function trigger watching for uploading blob, then this image will be resized and uploaded as 2 new images. 


```
   [FunctionName("DancersPhotoResizer")]
        public static async Task RunDancers(
            [BlobTrigger("dancers/{id}/{folder}/original/{name}", Connection = Constants.StorageConnectionString)]
            Stream image,
            int id, string folder, string name,
            [Blob("dancers/{id}/{folder}/full/{name}", FileAccess.Write, Connection =
                Constants.StorageConnectionString)]
            Stream fullImage,
            TraceWriter log,
            [Blob("dancers/{id}/{folder}/homepage/{name}", FileAccess.Write, Connection =
                Constants.StorageConnectionString)]
            Stream homepageImage, [Inject] FlymarkContext db
        ) // output blobs
        {
            await DoJob(image, id, folder, name, fullImage, homepageImage, db, PhotoTypeEnum.Dancer, AzureUploaderRepository.DancerContainer, log);
        }

```


```
[6/11/2018 3:01:49 AM] A ScriptHost error has occurred
[6/11/2018 3:01:49 AM] Exception while executing function: DancersPhotoResizer. Microsoft.Azure.WebJobs.Host: Error while handling parameter fullImage after function returned:. Microsoft.WindowsAzure.Storage: The remote server returned an error: (500) Internal Server Error.
[6/11/2018 3:01:49 AM] Exception while executing function: DancersPhotoResizer
[6/11/2018 3:01:49 AM] Exception while executing function: DancersPhotoResizer. Microsoft.Azure.WebJobs.Host: Error while handling parameter fullImage after function returned:. Microsoft.WindowsAzure.Storage: The remote server returned an error: (500) Internal Server Error.
[6/11/2018 3:01:49 AM] Function completed (Failure, Id=dc21faa8-c2f1-40f0-ad32-a965e989e314, Duration=33938ms)
[6/11/2018 3:01:49 AM]
[6/11/2018 3:01:49 AM] Executed 'DancersPhotoResizer' (Failed, Id=dc21faa8-c2f1-40f0-ad32-a965e989e314)
[6/11/2018 3:01:49 AM] mscorlib: Exception while executing function: DancersPhotoResizer. Microsoft.Azure.WebJobs.Host: Error while handling parameter fullImage after function returned:. Microsoft.WindowsAzure.Storage: The remote server returned an error: (500) Internal Server Error.
[6/11/2018 3:01:49 AM]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is 'dc21faa8-c2f1-40f0-ad32-a965e989e314'
[6/11/2018 3:01:49 AM] mscorlib: Exception while executing function: DancersPhotoResizer. Microsoft.Azure.WebJobs.Host: Error while handling parameter fullImage after function returned:. Microsoft.WindowsAzure.Storage: The remote server returned an error: (500) Internal Server Error.
```

**Comment by vovikdrg** [comment]
I've enabled logs [Verbose05-Nov-18-20-11.zip](https://github.com/Azure/azure-storage-net/files/2551443/Verbose05-Nov-18-20-11.zip)
By the way upload from storage explorer, and upload directly from js using SAS tokens works..

**Comment by smalgin** [comment]
I have the same issue.

I enabled logging and I see this immediately when I start Azure Storage Emulator 5.8

`11/15/2018 2:14:33 PM [Error_debug] [ActivityId=100dec59-2dd1-404d-80ca-16d8d3d24f00] Exception raised during processing of request. Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
`

Blob upload operations fail.

**Comment by ryancole** [comment]
Having same issue here using `UploadFromStreamAsync`.

**Comment by dfbaskin** [comment]
I'm seeing the same error.

**Comment by dfbaskin** [comment]
Changing the configuration from:

```
  <SQLInstance>.</SQLInstance>
```

to

```
  <SQLInstance>(localdb)\MSSQLLocalDB</SQLInstance>
```

made no difference.

**Comment by pavel-petrenko** [comment]
I got same error.
Next steps solve that issue.

1) open Windows Azure Storage Emulator 5.8.0.0 command line tool
2) run 
AzureStorageEmulator.exe stop
AzureStorageEmulator.exe clear
AzureStorageEmulator.exe init
AzureStorageEmulator.exe clear all
**AzureStorageEmulator.exe clear blob**
AzureStorageEmulator.exe start

**Comment by kfarmer-msft** [comment]
v5.9 is in the process of being published, and should resolve the null ref in CommitBlobImplV2.  I'll close this and update #810 when I update the fwlink.

**Comment by kfarmer-msft** [comment]
Everything should be live now.
