### ISSUE TITLE
The generated SAS URI for blob does not open the blob

### ISSUE THREAD

**Issue by nemrism** [Azure/azure-storage-net#804]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

9.4 / Emulator 5.8

### Which platform are you using? (ex: .NET Core 2.1)

.NET Framework 4.7

### What problem was encountered?

Unable to download a blob after generating its SAS URI

### How can we reproduce the problem in the simplest way?

1. Right click in UI on a blob
2. Generate SAS URI
3. Try to download it

### Have you found a mitigation/solution?

Nope

### Storage Emulator logs

**Info log:**
```
[Info_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Setting status description as "Server encountered an internal error. Please try again after some time."
```

**Error log:**
```
[Error_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Exception raised during processing of request. Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
```

**Unhandled log**
```
[UnhandledException] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)
```

**Verbose log**
```
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Accepting request
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Got request PUT http://127.0.0.1:10000/devstoreaccount1/maincontainer/670d8d88-c68a-4949-8e6a-956c5e1c9673.MP4?comp=blocklist 2015-12-11
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Host-style URI resolution failed. Allowing path-style for uri http://127.0.0.1:10000/devstoreaccount1/maincontainer/670d8d88-c68a-4949-8e6a-956c5e1c9673.MP4?comp=blocklist
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] StorageAccount.GetPropertiesImpl(PropertyNames=0x0020, ServiceMetadataPropertyNames=0x000000007807C000,,00:00:30)
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Returning from AcceptRequest method.
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Setting status code to 500
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] In the process end callback
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Entering BasicHttpRestProcessor.EndProcess
```

**Comment by kfarmer-msft** [comment]
Try using v5.9 of the emulator, which corrects an issue that would lead to that particular stack trace.
