### ISSUE TITLE
Bad Exception Message in case of a wrong Content MD5

### ISSUE THREAD

**Issue by amit9oct** [Azure/azure-storage-net#855]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.3.0

### Which platform are you using? (ex: .NET Core 2.1)
NET Core 2.0

### What problem was encountered?
I got an exception when I was trying to use `PutBlockAsync` with a bad value in `contentMD5` (something like: `0x8D6941119889C4E`). I know I should expect an exception because the MD5 is wrong. But the exception message doesn't really help me debug or even understand what is the issue. In fact it confuses me more because it goes something like `"Invalid length for a Base-64 char array or string"`. The first thing which comes to my mind after reading this is something must be wrong with the `blockId` because it is supposed to be a *Base64* string and should be shorter than 64 bytes etc.
Exception Trace:
```
System.AggregateException: One or more errors occurred. (Invalid length for a Base-64 char array or string.) ---> Microsoft.WindowsAzure.Storage.StorageException: Invalid length for a Base-64 char array or string. ---> System.FormatException: Invalid length for a Base-64 char array or string.
    at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpContentFactory.BuildContentFromStream[T](Stream stream, Int64 offset, Nullable`1 length, String md5, RESTCommand`1 cmd, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Shared\Protocol\HttpContentFactory.cs:line 36
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass84_0.<PutBlockImpl>b__0(RESTCommand`1 cmd, OperationContext ctx) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Blob\CloudBlockBlob.cs:line 1469
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 84
--- End of inner exception stack trace ---
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<PutBlockAsync>d__62.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Blob\CloudBlockBlob.cs:line 1020
--- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

### How can we reproduce the problem in the simplest way?
```
var cloudStorageAccount = storageAccount;
var cloudBlobClient = cloudStorageAccount.CreateCloudBlobClient();
var cloudBlockBlob = cloudBlobClient.GetContainerReference("blockblobutilstest")
	.GetBlockBlobReference("BadExceptionBlob");
var wrongContentMd5 = "0x8D6941119889C4E";
var spaceStream = new MemoryStream(Enumerable.Repeat((byte)0x20, 10240 /*10kB*/).ToArray());
cloudBlockBlob.PutBlockAsync(
	"TWV0YV8wMDAwMDAwMDAwMDAwMDAwMDAwXzAwMDAwMDAwMDAwMDAwMTAyNDBfMDAwMDAwMDAwMD0=", spaceStream, wrongContentMd5).Wait();
```
**#NOTE:** Obviously the original code was convoluted enough so that I couldn't easily figure out that `contentMD5` was wrong. Somehow because the block name has to be a **Base64** string I was only considering that as culprit. (Yes I know `contentMD5` is also stored as **Base64** `string` but since there is an explicit caution issued in the documentation ([CloudBlockBlob.PutBlock Method (Microsoft.WindowsAzure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblockblob.putblock?view=azure-dotnet) ) regarding `blockId` and NOT `contentMD5` one can easily be fooled into thinking that `blockId` is the reason for this issue.

### Have you found a mitigation/solution?
I don't know if I should call this a solution, either don't pass `contentMD5` or pass the right one.
```
var cloudStorageAccount = storageAccount;
var cloudBlobClient = cloudStorageAccount.CreateCloudBlobClient();
var cloudBlockBlob = cloudBlobClient.GetContainerReference("blockblobutilstest")
	.GetBlockBlobReference("BadExceptionBlob");
var spaceStream = new MemoryStream(Enumerable.Repeat((byte)0x20, 10240 /*10kB*/).ToArray());
cloudBlockBlob.PutBlockAsync(
	"TWV0YV8wMDAwMDAwMDAwMDAwMDAwMDAwXzAwMDAwMDAwMDAwMDAwMTAyNDBfMDAwMDAwMDAwMD0=", spaceStream, null).Wait();
```
### My suggestion ?
There can be multiple things which can be done:
. Have an explicit data type for Base64 string, so that one doesn't have to refer documentation every-time.
. Or simply have a better exception message which assists people in figuring out what might have gone wrong. Some message like *"`contentMD5` or `blockId` might be wrong please check"* might be a very helpful and save valuable man hours for people.

Thanks A Lot,
Amitayush Thakur

**Comment by seanmcc-msft** [comment]
Thank you for your suggestion, we are forwarding this issue to our backend team.
