### ISSUE TITLE
I am getting an error when I am running this command. TestCLI.exe -process <%GitHubDir%>\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\sample_images

### ISSUE THREAD

**Issue by j-ankur** [Azure/azure-storage-net#887]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which platform are you using? (ex: .NET Core 2.1)
.NET 4.5

### What problem was encountered?
Unable to run TESTCLI.exe -process command

### Have you found a mitigation/solution?
No

**Comment by j-ankur** [comment]
D:\Lab2-Implement_Computer_Vision\code\Starting-ImageProcessing\TestCLI\bin\Debug>TESTCLI.exe -process D:\Lab2-Implement_Computer_Vision\sample_images

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 54
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.<>c__DisplayClass24.<CreateContainerImpl>b__23(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 2513
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 51
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.EndCreate(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 133
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.EndCreateIfNotExists(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 329
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ImageStorageLibrary.BlobStorageHelper.<BuildAsync>d__8.MoveNext() in D:\Lab2-Implement_Computer_Vision\code\Starting-ImageProcessing\ImageStorageLibrary\BlobStorageHelper.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestCLI.Program.<InitializeAsync>d__3.MoveNext() in D:\Lab2-Implement_Computer_Vision\code\Starting-ImageProcessing\TestCLI\Program.cs:line 74
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestCLI.Program.<>c__DisplayClass0_0.<Main>b__0() in D:\Lab2-Implement_Computer_Vision\code\Starting-ImageProcessing\TestCLI\Program.cs:line 33
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at TestCLI.Program.Main(String[] args) in D:\Lab2-Implement_Computer_Vision\code\Starting-ImageProcessing\TestCLI\Program.cs:line 53

**Comment by j-ankur** [comment]
Please help

**Comment by seanmcc-msft** [comment]
Can you post a sample of the code you are attempting to run?

**Comment by j-ankur** [comment]
public class ImageProcessor
    {
        // Step 2: Create the ProcessImageAsync method:
        public static async Task<ImageInsights> ProcessImageAsync(Func<Task<Stream>> imageStreamCallback, string imageId)
        {
            // Step 3: Set up an array that we'll fill in over the course of the processor:
            VisualFeature[] DefaultVisualFeaturesList = new VisualFeature[] { VisualFeature.Tags, VisualFeature.Description };

            // Step 4: Call the Computer Vision service and store the results in imageAnalysisResult:
            var imageAnalysisResult = await VisionServiceHelper.AnalyzeImageAsync(imageStreamCallback, DefaultVisualFeaturesList);

            // Step 5: Create an entry in ImageInsights:
            ImageInsights result = new ImageInsights
            {
                ImageId = imageId,
                Caption = imageAnalysisResult.Description.Captions[0].Text,
                Tags = imageAnalysisResult.Tags.Select(t => t.Name).ToArray()
            };

            // Step 6: Return results:
            return result;
        }

    }

**Comment by seanmcc-msft** [comment]
Unfortunately I don't think I'll be able to assist you.  It looks like you have a dependency that is calling Azure Storage with an invalid request, resulting in the StorageException - Bad Request (400).
