### ISSUE TITLE
Unobserved exception was rethrown by the finalizer thread while using Storage Client

### ISSUE THREAD

**Issue by shivamatri1** [Azure/azure-storage-net#908]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
WindowsAzure.Storage.8.1.1

### Which platform are you using? (ex: .NET Core 2.1)
Net461

### What problem was encountered?
We are noticing Object Disposed exceptions in the WindowsAzure.Storage stack. Stack trace is -

EventName="FormattedMessageEvent" FormattedMessage="Unobserved Task Exception: {0}" Argument0="System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)<---

### Have you found a mitigation/solution?
This seems to happen intermittently.

**Comment by kasobol-msft** [comment]
Fixed in 11.1.4 version 
PR: https://github.com/Azure/azure-storage-net/pull/985
