### ISSUE TITLE
Unexpected EDM type from the Table Service: Edm.Double.

### ISSUE THREAD

**Issue by JeremyCade** [Azure/azure-storage-net#914]
### Which service(blob, file, queue, table) does this issue concern?
table storage

### Which version of the SDK was used?
WindowsAzure.Storage 9.3.3 and
Microsoft.Azure.Cosmos.Table 1.0.1

### Which platform are you using? (ex: .NET Core 2.1)
.NET Core 2.2 

### What problem was encountered?
The following exception is encountered when retrieving entities from Table Storage that have properties of type Double that are not set (or are NaN). 

Entities were inserted with WindowsAzure.Storage 9.3.3 and retrieved with Microsoft.Azure.Cosmos.Table 1.0.1. 

```
System.AggregateException: One or more errors occurred. (Unexpected EDM type from the Table Service: Edm.Double.) ---> Microsoft.Azure.Cosmos.Table.StorageException: Unexpected EDM type from the Table Service: Edm.Double. ---> System.InvalidOperationException: Unexpected EDM type from the Table Service: Edm.Double.
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.TableOperationHttpResponseParsers.ReadSingleItem(JToken token, String& etag)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.TableOperationHttpResponseParsers.ReadQueryResponseUsingJsonParserMetadataAsync(Stream responseStream, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.TableOperationHttpResponseParsers.TableQueryPostProcessGenericAsync[TElement,TQueryType](Stream responseStream, Func`6 resolver, HttpResponseMessage resp, TableRequestOptions options, OperationContext ctx)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.TableQueryRESTCommandGenerator.<>c__DisplayClass0_0.<<GenerateCMDForTableQuery>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ProcessEndOfRequestAsync[T](ExecutionState`1 executionState, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   --- End of inner exception stack trace ---
```

### How can we reproduce the problem in the simplest way?
see: https://github.com/JeremyCade/bork.azure.tablestorage for an example of this behaviour.

Basic steps to reproduce: 

1) Insert an entity into table storage with WindowsAzure.Storage 9.3.3 library. 
2) Retrieve entity from table storage with Microsoft.Azure.Cosmos.Table 1.0.1
3) BORK!

### Have you found a mitigation/solution?
No. 

### Aside
Where is the source for `Microsoft.Azure.Cosmos.Table`?

**Comment by JeremyCade** [comment]
This behaviour still exists with `Microsoft.Azure.Cosmos.Table 1.0.4`

**Comment by seanmcc-msft** [comment]
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

**Comment by alex-erygin** [comment]
Have same error with Microsoft.Azure.Cosmos.Table 1.0.5.

**Comment by JeremyCade** [comment]
@alex-erygin continued via https://github.com/Azure/azure-cosmos-table-dotnet/issues/16
