### ISSUE TITLE
Can't view or delete blobs with %12 in the name.

### ISSUE THREAD

**Issue by joepetrakovich** [Azure/azure-storage-net#977]
### Which service(blob, file, queue, table) does this issue concern?
Blob service.

### Which version of the SDK was used?
Azure.Storage.Blobs v12.4

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.7.2

### What problem was encountered?
The SDK returns an XML exception when trying to delete a file that has **%12** in the name.  I tried different combinations like %1 and %24 but could only get it to fail with %12.  Stack trace is at the bottom.

### How can we reproduce the problem in the simplest way?
Upload a blob with a name like `hello%12.jpg` and then call `BlobClient.DeleteIfExists()` on it.

Our call looks like:

### Have you found a mitigation/solution?
No.

Stack trace:

System.Xml.XmlException: '"' is an unexpected token. Expecting white space. Line 1, position 50.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.DtdParserProxy.System.Xml.IDtdParserAdapter.Throw(Exception e)
   at System.Xml.DtdParser.Throw(String res, String arg, Int32 lineNo, Int32 linePos)
   at System.Xml.DtdParser.ParseExternalId(Token idTokenType, Token declType, String& publicId, String& systemId)
   at System.Xml.DtdParser.ParseInDocumentDtd(Boolean saveInternalSubset)
   at System.Xml.DtdParser.Parse(Boolean saveInternalSubset)
   at System.Xml.DtdParser.System.Xml.IDtdParser.ParseInternalDtd(IDtdParserAdapter adapter, Boolean saveInternalSubset)
   at System.Xml.XmlTextReaderImpl.ParseDtd()
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DeleteAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.<DeleteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DeleteInternal>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DeleteIfExistsInternal>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DeleteIfExists(DeleteSnapshotsOption snapshotsOption, BlobRequestConditions conditions, CancellationToken cancellationToken)

**Comment by joepetrakovich** [comment]
I'm assuming it's related to the URI since %12 is a URL encoding, but the error is XML related on the delete.

**Comment by joepetrakovich** [comment]
This one may be able to be closed.  

We found that the tool we were using to upload files to blob storage was properly encoding the URI to the blob, but NOT encoding the blob name itself.  Not exactly sure how that's possible but essentially the Uri was different than the blob name (not including the host and container name parts of the Uri).

When we Uri encoded the actual blob name as well, it fixed the issue.
